"""Version-controlled markdown as the source of truth for curated knowledge.

A JSON blob or a vector collection is a fine *index* and a poor *source of
truth*. Curated examples and business rules are the highest-value, most
carefully-reviewed artifacts in a text-to-SQL deployment, and they deserve the
same treatment as code:

* **Reviewable** -- a change to a golden query shows up as a readable diff in a
  pull request, not as an opaque row update.
* **Attributable** -- ``git blame`` says who added a rule and when.
* **Portable** -- a directory of markdown files moves between environments,
  gets templated, and can be generated by other tooling.
* **Recoverable** -- a bad edit is one ``git revert`` away.

So the layout is::

    knowledge/
      sql/
        total-revenue-by-region.md      <- one example per file
        active-customers-last-quarter.md
      rules/
        amounts-in-cents.md             <- one instruction per file

Each file is YAML frontmatter plus an optional markdown body for notes::

    ---
    question: What is total revenue by region?
    status: verified
    tags: [revenue, finance]
    ---
    ```sql
    SELECT region, SUM(amount_cents) / 100.0 AS revenue
    FROM orders GROUP BY region
    ```

    Excludes cancelled orders by convention.

The vector index, when present, is a **derived artifact** built from these
files -- never the other way round. That direction matters: it means the index
can always be deleted and rebuilt, and the files can be edited by hand without
the two drifting apart.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List, Optional

from vanna.capabilities.agent_memory import tenant_scope
from vanna.capabilities.knowledge import (
    Example,
    ExampleHit,
    ExampleStatus,
    ExampleStore,
    Instruction,
    InstructionOrigin,
    InstructionScope,
    InstructionStore,
    extract_tables,
    validate_sql_syntax,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from vanna.core.tool import ToolContext

logger = logging.getLogger(__name__)

_MAX_SLUG_LEN = 60
_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", re.DOTALL)
_SQL_BLOCK_RE = re.compile(r"```sql\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)


def slugify(text: str) -> str:
    """Turn text into a stable, filesystem-safe slug.

    Deterministic, so re-saving the same question overwrites its file rather
    than accumulating near-duplicates.
    """
    slug = re.sub(r"[^a-z0-9]+", "-", text.strip().lower()).strip("-")
    if len(slug) > _MAX_SLUG_LEN:
        slug = slug[:_MAX_SLUG_LEN].rstrip("-")
    return slug or "untitled"


def _parse_frontmatter(text: str) -> tuple:
    """Split a document into ``(frontmatter_dict, body)``.

    Returns ``({}, text)`` when there is no frontmatter, so a plain markdown
    file degrades to "body only" rather than raising.
    """
    try:
        import yaml
    except ImportError:  # pragma: no cover - PyYAML is a core dependency
        return {}, text

    match = _FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    try:
        data = yaml.safe_load(match.group(1)) or {}
    except Exception as e:
        logger.warning("Malformed YAML frontmatter: %s", e)
        return {}, match.group(2)
    return (data if isinstance(data, dict) else {}), match.group(2)


def _render_frontmatter(data: Dict) -> str:
    import yaml

    return "---\n" + yaml.safe_dump(data, sort_keys=False).rstrip() + "\n---\n"


class MarkdownExampleStore(ExampleStore):
    """An :class:`ExampleStore` backed by ``knowledge/sql/*.md``.

    Files are the source of truth and are re-read from disk on demand, so an
    example edited by hand (or pulled from git) takes effect without a restart.

    Tenancy uses a directory per tenant rather than a metadata field, because
    the filesystem is the isolation boundary here -- and a directory that does
    not exist cannot be read from by mistake.

    Args:
        root: Knowledge directory root. Files live under
            ``<root>/<tenant>/sql/``.
        dialect: SQL dialect for write-time validation and table extraction.
        single_tenant: Omit the tenant directory level. Use for deployments
            that will never be multi-tenant and want a flatter tree.
    """

    def __init__(
        self,
        root: str = "./knowledge",
        *,
        dialect: Optional[str] = None,
        single_tenant: bool = False,
        index: Optional[Any] = None,
    ) -> None:
        self.root = Path(root)
        self.dialect = dialect
        self.single_tenant = single_tenant
        # Optional ranked index. Without one, search falls back to the term
        # overlap below, which keeps this store dependency-free and keeps the
        # index a strict improvement rather than a requirement.
        self.index = index

    # ------------------------------------------------------------------
    # Paths
    # ------------------------------------------------------------------

    def _dir(self, context: "ToolContext") -> Path:
        if self.single_tenant:
            return self.root / "sql"
        return self.root / tenant_scope(context) / "sql"

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def _to_markdown(self, example: Example) -> str:
        front = {
            "question": example.question,
            "status": example.status.value,
            "id": example.id,
        }
        if example.data_source_id != "default":
            front["datasource"] = example.data_source_id
        if example.tags:
            front["tags"] = example.tags
        if example.tables:
            front["tables"] = example.tables
        if example.created_by:
            front["created_by"] = example.created_by
        if example.verified_by:
            front["verified_by"] = example.verified_by
        return f"{_render_frontmatter(front)}\n```sql\n{example.sql.strip()}\n```\n"

    def _from_markdown(self, path: Path, tenant: str) -> Optional[Example]:
        try:
            raw = path.read_text(encoding="utf-8")
        except Exception as e:
            logger.warning("Could not read %s: %s", path, e)
            return None

        front, body = _parse_frontmatter(raw)

        # SQL comes from a fenced block so the file renders correctly on GitHub
        # and in any editor preview. Frontmatter is a fallback for files
        # written by other tooling.
        sql_match = _SQL_BLOCK_RE.search(body)
        sql = sql_match.group(1).strip() if sql_match else str(front.get("sql", "")).strip()
        question = str(front.get("question") or front.get("nl") or "").strip()

        if not question or not sql:
            logger.warning("Skipping %s: needs both a question and SQL", path)
            return None

        try:
            status = ExampleStatus(str(front.get("status", "candidate")))
        except ValueError:
            status = ExampleStatus.CANDIDATE

        return Example(
            id=str(front.get("id") or path.stem),
            question=question,
            sql=sql,
            status=status,
            tenant_id=tenant,
            data_source_id=str(front.get("datasource", "default")),
            tables=list(front.get("tables") or extract_tables(sql, self.dialect)),
            tags=list(front.get("tags") or []),
            created_by=front.get("created_by"),
            verified_by=front.get("verified_by"),
        )

    def _load_all(self, context: "ToolContext") -> List[Example]:
        directory = self._dir(context)
        if not directory.is_dir():
            return []
        tenant = tenant_scope(context)
        examples = []
        for path in sorted(directory.glob("*.md")):
            example = self._from_markdown(path, tenant)
            if example is not None:
                examples.append(example)
        return examples

    def _path_for(self, context: "ToolContext", example: Example) -> Path:
        return self._dir(context) / f"{slugify(example.question)}.md"

    # ------------------------------------------------------------------
    # ExampleStore interface
    # ------------------------------------------------------------------

    async def add(
        self,
        context: "ToolContext",
        question: str,
        sql: str,
        *,
        status: ExampleStatus = ExampleStatus.CANDIDATE,
        data_source_id: str = "default",
        tags: Optional[List[str]] = None,
        dialect: Optional[str] = None,
    ) -> Example:
        effective_dialect = dialect or self.dialect
        error = validate_sql_syntax(sql, effective_dialect)
        if error:
            raise ValueError(f"Refusing to store an invalid example. {error}")

        example = Example(
            question=question,
            sql=sql,
            status=status,
            tenant_id=tenant_scope(context),
            data_source_id=data_source_id,
            tables=extract_tables(sql, effective_dialect),
            tags=tags or [],
            created_by=context.user.id,
        )
        path = self._path_for(context, example)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self._to_markdown(example), encoding="utf-8")
        self._index_one(context, example)
        return example

    async def search(
        self,
        context: "ToolContext",
        question: str,
        *,
        limit: int = 5,
        min_score: float = 0.0,
        verified_only: bool = False,
        data_source_id: Optional[str] = None,
    ) -> List[ExampleHit]:
        """Lexical ranking over the files.

        Reads from disk each call. That is deliberate for a file-backed store:
        an example edited in an editor or pulled from git is live immediately,
        and correctness matters more here than shaving a few milliseconds off a
        path already dominated by an LLM round trip.
        """
        from .knowledge import _terms  # shared tokeniser

        candidates = [
            e
            for e in self._load_all(context)
            if e.status != ExampleStatus.REJECTED
            and (not verified_only or e.status == ExampleStatus.VERIFIED)
            and (data_source_id is None or e.data_source_id == data_source_id)
        ]

        if self.index is not None:
            ranked = self._search_indexed(context, question, candidates, limit, min_score)
            if ranked is not None:
                return ranked

        query_terms = _terms(question)
        if not query_terms:
            return []

        hits = []
        for example in candidates:
            example_terms = _terms(example.question)
            if not example_terms:
                continue
            overlap = len(query_terms & example_terms)
            if not overlap:
                continue
            score = overlap / len(query_terms | example_terms)
            if example.status == ExampleStatus.VERIFIED:
                score *= 1.25
            if score >= min_score:
                hits.append(ExampleHit(example=example, score=round(score, 4)))

        hits.sort(key=lambda h: -h.score)
        return hits[:limit]

    def _search_indexed(
        self,
        context: "ToolContext",
        question: str,
        candidates: List[Example],
        limit: int,
        min_score: float,
    ) -> Optional[List[ExampleHit]]:
        """Rank through the configured index, or None to fall back.

        The index is brought into step with ``candidates`` on each call rather
        than trusted to be current. That matters because the markdown is the
        source of truth and someone may have just edited it in their editor --
        an index that disagrees with the files is the failure this store was
        designed to avoid.

        *How* it is brought into step is the index's business, not this store's.
        ``sync_documents`` rebuilds the in-process BM25 index outright, because
        doing so is sub-millisecond; for a persistent vector index it compares
        content hashes and re-embeds only what changed. This used to be a
        hard-coded clear-and-add here, which for a vector backend would have
        meant re-embedding the whole corpus once per question.
        """
        from vanna.capabilities.agent_memory import tenant_scope

        try:
            from vanna.capabilities.index import documents_for_examples, sync_documents

            tenant = tenant_scope(context)
            sync_documents(
                self.index,
                documents_for_examples(candidates, tenant_id=tenant),
                tenant_id=tenant,
                # This store owns examples and nothing else. Claiming a wider
                # scope would delete the catalog's table documents, which share
                # the index.
                kinds="example",
            )

            by_id = {f"example:{e.id}": e for e in candidates}
            hits = []
            for hit in self.index.search(question, tenant_id=tenant, limit=limit):
                example = by_id.get(hit.id)
                if example is not None and hit.score >= min_score:
                    hits.append(ExampleHit(example=example, score=round(hit.score, 4)))
            return hits
        except Exception as exc:
            # Retrieval degrading to the built-in ranking is far better than a
            # question failing because a search backend was unavailable.
            logger.warning("Index search failed, falling back to term overlap: %s", exc)
            return None

    async def list_all(
        self,
        context: "ToolContext",
        *,
        status: Optional[ExampleStatus] = None,
        data_source_id: Optional[str] = None,
    ) -> List[Example]:
        examples = self._load_all(context)
        if status is not None:
            examples = [e for e in examples if e.status == status]
        if data_source_id is not None:
            examples = [e for e in examples if e.data_source_id == data_source_id]
        return examples

    async def set_status(
        self,
        context: "ToolContext",
        example_id: str,
        status: ExampleStatus,
        *,
        actor: Optional[str] = None,
    ) -> bool:
        for example in self._load_all(context):
            if example.id != example_id:
                continue
            example.status = status
            if status == ExampleStatus.VERIFIED:
                example.verified_by = actor or context.user.id
            self._path_for(context, example).write_text(
                self._to_markdown(example), encoding="utf-8"
            )
            # Verifying an example raises its boost, so the stored entry is now
            # wrong even though its text is unchanged.
            self._index_one(context, example)
            return True
        return False

    async def delete(self, context: "ToolContext", example_id: str) -> bool:
        for example in self._load_all(context):
            if example.id == example_id:
                path = self._path_for(context, example)
                if path.exists():
                    path.unlink()
                    self._unindex_one(context, example)
                    return True
        return False

    # ------------------------------------------------------------------
    # Keeping a persistent index current
    #
    # A write knows exactly which document changed, so it updates that one
    # rather than leaving it to the next search to notice. For the in-process
    # index this is redundant -- it rebuilds on every search anyway -- and
    # harmless. For a persistent one it is the difference between a rule being
    # retrievable now and only after something else triggers a sync.
    # ------------------------------------------------------------------

    def _index_one(self, context: "ToolContext", example: Example) -> None:
        if self.index is None:
            return
        try:
            from vanna.capabilities.agent_memory import tenant_scope
            from vanna.capabilities.index import documents_for_examples, fingerprint

            documents = list(
                documents_for_examples([example], tenant_id=tenant_scope(context))
            )
            for document in documents:
                document.metadata.setdefault("fingerprint", fingerprint(document))
            self.index.add(documents)
        except Exception as exc:  # noqa: BLE001
            # The markdown is written and is the source of truth; a failed index
            # update costs freshness until the next sync, not the example.
            logger.warning("Could not index example %s: %s", example.id, exc)

    def _unindex_one(self, context: "ToolContext", example: Example) -> None:
        if self.index is None:
            return
        try:
            self.index.remove([f"example:{example.id}"])
        except Exception as exc:  # noqa: BLE001
            logger.warning("Could not unindex example %s: %s", example.id, exc)


class MarkdownInstructionStore(InstructionStore):
    """An :class:`InstructionStore` backed by ``knowledge/rules/*.md``.

    Business rules are exactly the kind of thing that should live in version
    control: they encode institutional knowledge, they are argued over, and
    "who decided amounts are in cents, and when?" is a question people
    genuinely ask months later.
    """

    def __init__(self, root: str = "./knowledge", *, single_tenant: bool = False):
        self.root = Path(root)
        self.single_tenant = single_tenant

    def _dir(self, context: "ToolContext") -> Path:
        if self.single_tenant:
            return self.root / "rules"
        return self.root / tenant_scope(context) / "rules"

    def _to_markdown(self, instruction: Instruction) -> str:
        front = {
            "id": instruction.id,
            "scope": instruction.scope.value,
            "enabled": instruction.enabled,
        }
        if instruction.scope_ref:
            front["scope_ref"] = instruction.scope_ref
        if instruction.priority:
            front["priority"] = instruction.priority
        if instruction.created_by:
            front["created_by"] = instruction.created_by
        # Provenance has to survive the round trip or a rule copied from a
        # starter pack silently becomes indistinguishable from a hand-written
        # one, and removing the pack would take the wrong rules with it.
        if instruction.origin != InstructionOrigin.TENANT:
            front["origin"] = instruction.origin.value
        if instruction.source_pack:
            front["source_pack"] = instruction.source_pack
        if instruction.updated_at:
            front["updated_at"] = instruction.updated_at.isoformat()
        return f"{_render_frontmatter(front)}\n{instruction.text.strip()}\n"

    def _from_markdown(self, path: Path, tenant: str) -> Optional[Instruction]:
        try:
            raw = path.read_text(encoding="utf-8")
        except Exception as e:
            logger.warning("Could not read %s: %s", path, e)
            return None
        front, body = _parse_frontmatter(raw)
        text = body.strip()
        if not text:
            logger.warning("Skipping %s: no rule text in the body", path)
            return None
        try:
            scope = InstructionScope(str(front.get("scope", "global")))
        except ValueError:
            scope = InstructionScope.GLOBAL
        try:
            origin = InstructionOrigin(str(front.get("origin", "tenant")))
        except ValueError:
            origin = InstructionOrigin.TENANT
        updated_raw = front.get("updated_at")
        updated_at = None
        if updated_raw:
            try:
                updated_at = datetime.fromisoformat(str(updated_raw))
            except ValueError:
                updated_at = None

        return Instruction(
            id=str(front.get("id") or path.stem),
            text=text,
            scope=scope,
            scope_ref=front.get("scope_ref"),
            tenant_id=tenant,
            priority=int(front.get("priority", 0) or 0),
            enabled=bool(front.get("enabled", True)),
            created_by=front.get("created_by"),
            origin=origin,
            source_pack=front.get("source_pack"),
            updated_at=updated_at,
        )

    def _load_all(self, context: "ToolContext") -> List[Instruction]:
        directory = self._dir(context)
        if not directory.is_dir():
            return []
        tenant = tenant_scope(context)
        out = []
        for path in sorted(directory.glob("*.md")):
            instruction = self._from_markdown(path, tenant)
            if instruction is not None:
                out.append(instruction)
        return out

    def _existing_path(self, directory: Path, instruction_id: str) -> Optional[Path]:
        """The file already holding this rule, found by id rather than by name."""
        if not directory.is_dir():
            return None
        for path in sorted(directory.glob("*.md")):
            try:
                front, _ = _parse_frontmatter(path.read_text(encoding="utf-8"))
            except Exception:  # pragma: no cover - unreadable file
                continue
            if str(front.get("id") or path.stem) == instruction_id:
                return path
        return None

    def _path_for(self, context: "ToolContext", instruction: Instruction) -> Path:
        """Where this rule's file lives.

        Named from the text so a diff is readable, but *found* by id, which
        fixes two bugs that were one line apart. The name used to be
        ``slugify(text[:60])`` alone: two rules sharing their first sixty
        characters resolved to the same file and the second silently destroyed
        the first, and editing a rule's wording moved it to a new path and left
        the old file behind, so the rule appeared twice.

        The id suffix only applies to new files. An existing one is found by
        its front-matter id and rewritten in place, so nothing already on disk
        is renamed -- including files written before this had a suffix at all.
        """
        directory = self._dir(context)
        existing = self._existing_path(directory, instruction.id)
        if existing is not None:
            return existing
        stem = slugify(instruction.text[:60]) or "rule"
        return directory / f"{stem}-{instruction.id[:8]}.md"

    async def add(
        self, context: "ToolContext", instruction: Instruction
    ) -> Instruction:
        if instruction.scope != InstructionScope.GLOBAL and not instruction.scope_ref:
            raise ValueError(
                f"Instructions scoped to '{instruction.scope.value}' require a "
                "scope_ref naming the data source, table, or group."
            )
        instruction.tenant_id = tenant_scope(context)
        if instruction.created_by is None:
            instruction.created_by = context.user.id
        path = self._path_for(context, instruction)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self._to_markdown(instruction), encoding="utf-8")
        return instruction

    async def resolve(
        self,
        context: "ToolContext",
        *,
        data_source_id: Optional[str] = None,
        tables: Optional[List[str]] = None,
    ) -> List[Instruction]:
        groups = list(getattr(context.user, "group_memberships", []) or [])
        applicable = [
            i
            for i in self._load_all(context)
            if i.applies_to(
                data_source_id=data_source_id, tables=tables, user_groups=groups
            )
        ]
        applicable.sort(key=lambda i: (-i.priority, i.id))
        return applicable

    async def list_all(self, context: "ToolContext") -> List[Instruction]:
        return sorted(self._load_all(context), key=lambda i: (-i.priority, i.id))

    async def set_enabled(
        self, context: "ToolContext", instruction_id: str, enabled: bool
    ) -> bool:
        for instruction in self._load_all(context):
            if instruction.id == instruction_id:
                instruction.enabled = enabled
                self._path_for(context, instruction).write_text(
                    self._to_markdown(instruction), encoding="utf-8"
                )
                return True
        return False

    async def update(
        self,
        context: "ToolContext",
        instruction_id: str,
        *,
        text: Optional[str] = None,
        scope: Optional[InstructionScope] = None,
        scope_ref: Optional[str] = None,
        priority: Optional[int] = None,
        enabled: Optional[bool] = None,
    ) -> Optional[Instruction]:
        for instruction in self._load_all(context):
            if instruction.id != instruction_id:
                continue

            # Resolve the new scope before validating, so changing only the
            # scope still gets checked against the existing scope_ref.
            new_scope = scope if scope is not None else instruction.scope
            new_ref = scope_ref if scope_ref is not None else instruction.scope_ref
            if new_scope != InstructionScope.GLOBAL and not new_ref:
                raise ValueError(
                    f"Instructions scoped to '{new_scope.value}' require a "
                    "scope_ref naming the data source, table, or group."
                )

            # The path is resolved from the *old* text, because that is what is
            # on disk; writing to it keeps the rule in one file.
            path = self._path_for(context, instruction)

            if text is not None:
                instruction.text = text
            instruction.scope = new_scope
            instruction.scope_ref = new_ref
            if priority is not None:
                instruction.priority = priority
            if enabled is not None:
                instruction.enabled = enabled
            instruction.updated_at = datetime.now(timezone.utc)

            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(self._to_markdown(instruction), encoding="utf-8")
            return instruction
        return None

    async def delete(self, context: "ToolContext", instruction_id: str) -> bool:
        for instruction in self._load_all(context):
            if instruction.id == instruction_id:
                path = self._path_for(context, instruction)
                if path.exists():
                    path.unlink()
                    return True
        return False
