"""Instructions in the control plane, against a real database.

Rules used to be markdown files named after a slug of their own text, and two
bugs followed from that naming rather than from anything anybody wrote:

* two rules sharing their first sixty characters resolved to the same filename,
  so adding the second silently destroyed the first;
* editing a rule's wording moved it to a new filename and left the old file in
  place, so the rule appeared twice and the stale copy kept reaching the prompt.

Both are pinned in :class:`TestTheBugsThatMotivatedTheMove`, parametrised across
the markdown and Postgres stores, and both were checked to fail against the
unfixed markdown store rather than merely assumed to. The markdown store is still
shipped -- it is the demo-mode fallback and the library's default -- so it had to
be fixed, not abandoned.

The rest is what moving to a database is *for*: an id that survives an edit,
isolation enforced by a column rather than by a directory, pack bookkeeping that
can be a transaction, and rows that disappear when the workspace does.
"""

from __future__ import annotations

from types import SimpleNamespace

import pytest

from vanna.capabilities.knowledge import (
    Instruction,
    InstructionOrigin,
    InstructionScope,
)

pytestmark = pytest.mark.integration


@pytest.fixture
def tenants(app_db):
    """Two workspaces, because the isolation tests need somewhere to leak to."""

    async def make() -> None:
        for tenant in ("acme", "globex"):
            await app_db.execute(
                "INSERT INTO vanna_app.tenants (id, name) VALUES (%s, %s) "
                "ON CONFLICT (id) DO NOTHING",
                (tenant, tenant.title()),
            )

    return make


@pytest.fixture
async def store(app_db, tenants):
    from vanna_app.instruction_store import PostgresInstructionStore

    await tenants()
    return PostgresInstructionStore(app_db)


@pytest.fixture
def acme(tool_context):
    return tool_context("acme", "ada@acme.example")


@pytest.fixture
def globex(tool_context):
    return tool_context("globex", "bob@globex.example")


class TestRoundTrip:
    async def test_add_list_and_delete(self, store, acme):
        created = await store.add(acme, Instruction(text="Revenue excludes tax."))
        assert created.id

        listed = await store.list_all(acme)
        assert [r.text for r in listed] == ["Revenue excludes tax."]
        assert listed[0].origin == InstructionOrigin.TENANT

        assert await store.delete(acme, created.id) is True
        assert await store.list_all(acme) == []

    async def test_deleting_something_absent_is_false_not_an_error(self, store, acme):
        assert await store.delete(acme, "00000000-0000-0000-0000-000000000000") is False

    async def test_add_is_an_insert_not_an_upsert(self, store, acme):
        """Stated rather than discovered.

        The id is generated by the database, so passing the same `Instruction`
        twice stores it twice. Every caller that could repeat -- the pack copier,
        the markdown importer, the domain provisioner -- deduplicates on text
        before calling this, which is why that is safe.
        """
        rule = Instruction(text="Said once.")
        await store.add(acme, rule)
        await store.add(acme, rule)
        assert len(await store.list_all(acme)) == 2

    async def test_provenance_survives_the_round_trip(self, store, acme):
        created = await store.add(
            acme,
            Instruction(
                text="From a pack.",
                origin=InstructionOrigin.LIBRARY,
                source_pack="finance-conventions",
            ),
        )
        loaded = (await store.list_all(acme))[0]
        assert loaded.origin == InstructionOrigin.LIBRARY
        assert loaded.source_pack == "finance-conventions"
        assert created.source_pack == "finance-conventions"

    async def test_a_platform_rule_cannot_be_stored_against_a_tenant(self, store, acme):
        """The baseline is merged at read time; a row would be a second copy."""
        with pytest.raises(ValueError):
            await store.add(
                acme,
                Instruction(text="Platform.", origin=InstructionOrigin.PLATFORM),
            )

    async def test_a_scoped_rule_needs_a_reference(self, store, acme):
        with pytest.raises(ValueError):
            await store.add(
                acme, Instruction(text="x", scope=InstructionScope.TABLE)
            )


class TestTheBugsThatMotivatedTheMove:
    """Parametrised over both stores: the markdown one is still shipped."""

    @pytest.fixture(params=["postgres", "markdown"])
    def either(self, request, app_db, tmp_path, tenants):
        async def build():
            await tenants()
            if request.param == "postgres":
                from vanna_app.instruction_store import PostgresInstructionStore

                return PostgresInstructionStore(app_db)
            from vanna.integrations.local import MarkdownInstructionStore

            return MarkdownInstructionStore(str(tmp_path / "knowledge"))

        return build

    #: Identical for sixty-one characters, different after. The old filename was
    #: `slugify(text[:60])`, so both landed on the same path.
    LONG_A = "Exclude cancelled orders from every revenue figure we report, always."
    LONG_B = "Exclude cancelled orders from every revenue figure we report, never."

    async def test_two_rules_with_the_same_first_sixty_characters_both_survive(
        self, either, acme
    ):
        store = await either()
        await store.add(acme, Instruction(text=self.LONG_A))
        await store.add(acme, Instruction(text=self.LONG_B))

        texts = sorted(r.text for r in await store.list_all(acme))
        assert texts == sorted([self.LONG_A, self.LONG_B]), (
            "one rule overwrote the other -- identity must not come from the text"
        )

    async def test_editing_the_text_keeps_one_rule_with_the_same_id(
        self, either, acme
    ):
        store = await either()
        created = await store.add(acme, Instruction(text="Original wording."))

        updated = await store.update(acme, created.id, text="Rewritten wording.")
        assert updated is not None
        assert updated.id == created.id, "an edit must not mint a new rule"

        listed = await store.list_all(acme)
        assert len(listed) == 1, f"editing orphaned a copy: {[r.text for r in listed]}"
        assert listed[0].text == "Rewritten wording."

    async def test_an_edit_is_visible_to_the_next_reader(self, either, acme):
        store = await either()
        created = await store.add(acme, Instruction(text="Before."))
        await store.update(acme, created.id, priority=99)
        assert (await store.list_all(acme))[0].priority == 99

    async def test_rewriting_a_file_backed_rule_leaves_no_stale_copy(
        self, tmp_path, acme
    ):
        """The orphan bug, reached directly -- and it is the markdown store's alone.

        `update` sidesteps it by resolving the path before it mutates the text,
        so only re-saving an existing rule gets there. Under the old naming the
        second write landed on a filename derived from the new text, the first
        file stayed put, and the rule was then in the prompt twice with two
        different wordings.

        Not parametrised: the Postgres store has no filenames and no equivalent
        failure, and `add` there is an INSERT -- see
        :meth:`TestRoundTrip.test_add_is_an_insert_not_an_upsert`.
        """
        from vanna.integrations.local import MarkdownInstructionStore

        store = MarkdownInstructionStore(str(tmp_path / "knowledge"))
        rule = Instruction(text="Original wording.")
        await store.add(acme, rule)

        rule.text = "Rewritten wording."
        await store.add(acme, rule)

        listed = await store.list_all(acme)
        assert len(listed) == 1, f"a stale copy survived: {[r.text for r in listed]}"
        assert listed[0].text == "Rewritten wording."


class TestIsolation:
    async def test_one_workspace_cannot_read_another_s_rules(
        self, store, acme, globex
    ):
        await store.add(acme, Instruction(text="Acme only."))
        assert await store.list_all(globex) == []

    async def test_one_workspace_cannot_delete_another_s_rule(
        self, store, acme, globex
    ):
        created = await store.add(acme, Instruction(text="Acme only."))
        assert await store.delete(globex, created.id) is False
        assert len(await store.list_all(acme)) == 1

    async def test_one_workspace_cannot_edit_another_s_rule(self, store, acme, globex):
        created = await store.add(acme, Instruction(text="Acme only."))
        assert await store.update(globex, created.id, text="Hijacked.") is None
        assert (await store.list_all(acme))[0].text == "Acme only."

    async def test_deleting_a_workspace_takes_its_rules(self, store, app_db, acme):
        await store.add(acme, Instruction(text="Acme only."))
        await app_db.execute("DELETE FROM vanna_app.tenants WHERE id = %s", ("acme",))

        remaining = await app_db.fetch_value(
            "SELECT count(*) FROM vanna_app.instructions WHERE tenant_id = %s",
            ("acme",),
            default=0,
        )
        assert int(remaining) == 0, "the foreign key should have cascaded"


class TestBaselineOverrides:
    async def test_an_override_is_recorded_and_cleared(self, store, acme):
        assert await store.disabled_ids(acme) == set()

        await store.set_disabled(acme, "platform.explicit-columns", True)
        assert await store.disabled_ids(acme) == {"platform.explicit-columns"}

        await store.set_disabled(acme, "platform.explicit-columns", False)
        assert await store.disabled_ids(acme) == set(), (
            "re-enabling must remove the exception, not store a false"
        )

    async def test_overrides_do_not_cross_workspaces(self, store, acme, globex):
        await store.set_disabled(acme, "platform.explicit-columns", True)
        assert await store.disabled_ids(globex) == set()

    async def test_disabling_twice_is_idempotent(self, store, acme):
        await store.set_disabled(acme, "platform.explicit-columns", True)
        await store.set_disabled(acme, "platform.explicit-columns", True)
        assert await store.disabled_ids(acme) == {"platform.explicit-columns"}


class TestStarterPacks:
    @pytest.fixture
    def pack(self):
        from vanna_app.instruction_library import Pack

        return Pack(
            id="finance-conventions",
            name="Finance conventions",
            description="",
            instructions=[
                Instruction(text="Amounts in _cents are integer cents.", priority=60),
                Instruction(text="Exclude refunds from revenue.", priority=55),
            ],
        )

    async def test_enabling_copies_the_rules_in(self, store, acme, pack):
        added, skipped = await store.copy_pack(acme, pack)
        assert (added, skipped) == (2, 0)

        rules = await store.list_all(acme)
        assert {r.origin for r in rules} == {InstructionOrigin.LIBRARY}
        assert {r.source_pack for r in rules} == {"finance-conventions"}
        assert await store.enabled_packs(acme) == {"finance-conventions"}

    async def test_enabling_twice_adds_nothing_the_second_time(
        self, store, acme, pack
    ):
        await store.copy_pack(acme, pack)
        added, skipped = await store.copy_pack(acme, pack)
        assert added == 0 and skipped == 2
        assert len(await store.list_all(acme)) == 2

    async def test_a_rule_already_written_by_hand_is_not_duplicated(
        self, store, acme, pack
    ):
        await store.add(acme, Instruction(text="Exclude refunds from revenue."))
        added, skipped = await store.copy_pack(acme, pack)
        assert (added, skipped) == (1, 1)

    async def test_removing_a_pack_keeps_an_edited_copy(self, store, acme, pack):
        """Once somebody has reworded a rule it is theirs, and removing the pack
        it arrived in must not delete their work."""
        await store.copy_pack(acme, pack)
        mine = next(
            r for r in await store.list_all(acme) if "refunds" in r.text
        )
        await store.update(acme, mine.id, text="Exclude refunds and chargebacks.")

        removed, kept = await store.remove_pack(acme, "finance-conventions")
        assert (removed, kept) == (1, 1)

        left = await store.list_all(acme)
        assert [r.text for r in left] == ["Exclude refunds and chargebacks."]
        assert await store.enabled_packs(acme) == set()

    async def test_removing_an_untouched_pack_takes_all_of_it(
        self, store, acme, pack
    ):
        await store.copy_pack(acme, pack)
        removed, kept = await store.remove_pack(acme, "finance-conventions")
        assert (removed, kept) == (2, 0)
        assert await store.list_all(acme) == []


class TestMarkdownImport:
    @pytest.fixture
    def markdown(self, tmp_path):
        from vanna.integrations.local import MarkdownInstructionStore

        return MarkdownInstructionStore(str(tmp_path / "knowledge"))

    async def test_it_brings_the_files_across(self, store, markdown, acme):
        await markdown.add(acme, Instruction(text="From a file.", priority=7))
        assert await store.import_from(acme, markdown) == 1

        imported = await store.list_all(acme)
        assert [r.text for r in imported] == ["From a file."]
        assert imported[0].priority == 7

    async def test_running_it_twice_imports_nothing_new(self, store, markdown, acme):
        await markdown.add(acme, Instruction(text="From a file."))
        await store.import_from(acme, markdown)
        assert await store.import_from(acme, markdown) == 0

    async def test_the_marker_is_what_stops_a_deleted_rule_returning(
        self, store, app_db, markdown, acme
    ):
        """The condition that looks obvious -- import when the table is empty --
        resurrects every rule an administrator deliberately deleted."""
        from vanna_app.instruction_store import claim_import, needs_import

        await markdown.add(acme, Instruction(text="From a file."))
        assert await needs_import(app_db, "acme") is True

        assert await claim_import(app_db, "acme") is True
        await store.import_from(acme, markdown)

        for rule in await store.list_all(acme):
            await store.delete(acme, rule.id)

        assert await needs_import(app_db, "acme") is False, (
            "a second import would bring the deleted rule back"
        )

    async def test_only_one_worker_can_claim_the_import(self, app_db, tenants):
        """Four uvicorn workers race here, and two of them won.

        The first version marked the workspace as imported *after* copying the
        rules. Two workers both saw "not imported", both read an empty table, and
        both inserted -- which produced two of every rule on the first real
        workspace this ran against. The claim now happens first.
        """
        from vanna_app.instruction_store import claim_import, release_import

        await tenants()
        assert await claim_import(app_db, "acme") is True
        assert await claim_import(app_db, "acme") is False, (
            "a second worker claimed an import that was already taken"
        )

        # A worker that fails hands the claim back rather than losing the rules.
        await release_import(app_db, "acme")
        assert await claim_import(app_db, "acme") is True

    async def test_a_failed_import_is_retried(self, app_db, markdown, acme, tenants):
        from vanna_app.instruction_store import PostgresInstructionStore, needs_import

        await tenants()
        store = PostgresInstructionStore(app_db)
        await markdown.add(acme, Instruction(text="From a file."))

        class Broken(PostgresInstructionStore):
            async def import_from(self, context, source):
                raise RuntimeError("control plane went away")

        platform = SimpleNamespace(
            tenant_instructions=Broken(app_db),
            markdown_instructions=markdown,
            system_context=lambda tenant_id: acme,
        )
        from vanna_app.platform import Platform

        await Platform.ensure_instructions_imported(platform, "acme")

        assert await needs_import(app_db, "acme") is True, (
            "a failed import kept the claim, so the rules would never arrive"
        )
