"""Schema catalog data models.

The catalog is the structural knowledge the agent has about a database: what
tables exist, what their columns mean, how they join, and -- crucially -- what
values the enum-like columns actually hold.

This is deliberately separate from ``AgentMemory``. The dividing line:

* **Catalog** -- structural facts *derived from* the database. Regenerated by
  scanning. Authoritative. Goes stale when the schema changes, and knows it.
* **Memory** -- semantic facts *asserted by* humans or learned from
  interactions. Never derivable from the database. Advisory.

Blurring the two produces a store where nobody can tell which entries a rescan
may safely overwrite.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class CatalogStatus(str, Enum):
    """Freshness of a catalog entry.

    Tracked explicitly because stale metadata is worse than none: an agent
    confidently writing SQL against a column dropped last week produces an
    error the user cannot interpret. A catalog that knows it is stale can say
    so.
    """

    NOT_SCANNED = "not_scanned"
    SCANNING = "scanning"
    SCANNED = "scanned"
    STALE = "stale"
    FAILED = "failed"


class ForeignKey(BaseModel):
    """A foreign-key reference from one column to another table."""

    column: str = Field(description="Column in this table holding the reference")
    references_table: str = Field(description="Table being referenced")
    references_column: str = Field(description="Column being referenced")


class ColumnMetadata(BaseModel):
    """A single column's structure and, where cheap to learn, its contents."""

    name: str
    data_type: str = "unknown"
    nullable: bool = True
    is_primary_key: bool = False
    description: Optional[str] = Field(
        default=None,
        description="Human-authored meaning. Worth far more to generation "
        "accuracy than the type, which the model can usually infer.",
    )

    # -- Write-shape facts. Irrelevant to reading, load-bearing for writing:
    #    together with `nullable` they decide what an INSERT must supply and
    #    what an assignment may name. Both default to the permissive-to-read,
    #    restrictive-to-write answer, so a catalog scanned before these existed
    #    stays valid and simply offers fewer assignable columns.
    is_generated: bool = Field(
        default=False,
        description="Identity or computed column. The database refuses an "
        "assignment to one, so a write plan may never name it -- though it is "
        "still addressable in a predicate when it is the primary key, which "
        "a generated surrogate key usually is.",
    )
    has_default: bool = Field(
        default=False,
        description="A DEFAULT expression exists, so an INSERT that omits this "
        "column still produces a valid row.",
    )

    low_cardinality: bool = Field(
        default=False,
        description="True when the column holds a small, closed set of values "
        "-- i.e. it is enum-like.",
    )
    categories: Optional[List[str]] = Field(
        default=None,
        description=(
            "The actual distinct values, when the column is low-cardinality. "
            "This is the single highest-value field in the catalog: the most "
            "common cause of wrong-but-valid SQL is an invented literal "
            "(WHERE status = 'active' when the column stores 'ACTIVE'). "
            "Knowing the real values eliminates that class of error before "
            "the query is written, with no extra round trip."
        ),
    )

    foreign_key: Optional[ForeignKey] = None
    sample_values: Optional[List[str]] = Field(
        default=None,
        description="A few representative values for high-cardinality columns, "
        "conveying format (date layout, id shape) without enumerating the "
        "domain. Subject to redaction -- see SchemaScanner.",
    )

    @property
    def required_on_insert(self) -> bool:
        """Whether an INSERT that omits this column produces a row the database refuses.

        The three escapes are the only three there are: the column accepts
        NULL, the database computes it, or a DEFAULT fills it in.
        """
        return not (self.nullable or self.is_generated or self.has_default)

    def describe(self) -> str:
        """One-line rendering for a prompt."""
        parts = [f"{self.name} ({self.data_type}"]
        if self.is_primary_key:
            parts.append(", PK")
        if not self.nullable:
            parts.append(", NOT NULL")
        if self.is_generated:
            parts.append(", generated")
        parts.append(")")
        line = "".join(parts)

        if self.description:
            line += f" -- {self.description}"
        if self.foreign_key:
            fk = self.foreign_key
            line += f" [FK -> {fk.references_table}.{fk.references_column}]"
        if self.categories:
            shown = ", ".join(repr(c) for c in self.categories[:20])
            more = "" if len(self.categories) <= 20 else f", +{len(self.categories) - 20} more"
            line += f" [values: {shown}{more}]"
        elif self.sample_values:
            shown = ", ".join(repr(v) for v in self.sample_values[:3])
            line += f" [e.g. {shown}]"
        return line


class TableMetadata(BaseModel):
    """A table, its columns, and its provenance."""

    table_name: str
    schema_name: Optional[str] = None
    description: Optional[str] = None
    columns: List[ColumnMetadata] = Field(default_factory=list)

    row_count_estimate: Optional[int] = Field(
        default=None,
        description="Approximate row count. Lets the agent prefer aggregation "
        "over row-by-row retrieval on large tables.",
    )

    # -- Scoping. Present on the record itself so a store cannot return a row
    #    without the caller being able to verify who it belongs to.
    tenant_id: str = "default"
    data_source_id: str = "default"

    # -- Provenance
    status: CatalogStatus = CatalogStatus.SCANNED
    last_synced_at: Optional[datetime] = None
    error_message: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @property
    def qualified_name(self) -> str:
        """``schema.table`` when a schema is known, else just ``table``."""
        if self.schema_name:
            return f"{self.schema_name}.{self.table_name}"
        return self.table_name

    @property
    def primary_keys(self) -> List[str]:
        return [c.name for c in self.columns if c.is_primary_key]

    def get_column(self, name: str) -> Optional[ColumnMetadata]:
        """Case-insensitive column lookup."""
        lowered = name.lower()
        for column in self.columns:
            if column.name.lower() == lowered:
                return column
        return None

    def is_stale(self, max_age_hours: float = 24.0) -> bool:
        """True if this entry has not been refreshed recently."""
        if self.status in (CatalogStatus.STALE, CatalogStatus.NOT_SCANNED):
            return True
        if self.last_synced_at is None:
            return True
        synced = self.last_synced_at
        if synced.tzinfo is None:
            synced = synced.replace(tzinfo=timezone.utc)
        age = (datetime.now(timezone.utc) - synced).total_seconds() / 3600.0
        return age > max_age_hours

    def describe(self, *, include_columns: bool = True) -> str:
        """Structured plain-text rendering for a prompt."""
        lines = [f"### Table: {self.qualified_name}"]
        if self.description:
            lines.append(f"  {self.description}")
        if self.row_count_estimate is not None:
            lines.append(f"  Approximate rows: {self.row_count_estimate:,}")
        if include_columns and self.columns:
            lines.append("  Columns:")
            lines.extend(f"    - {c.describe()}" for c in self.columns)
        return "\n".join(lines)


class RelationshipMetadata(BaseModel):
    """A join path between two tables.

    Stated explicitly because join paths are exactly what chunked retrieval
    destroys: fetching three tables in isolation loses the edges between them,
    which is the information a multi-table query actually needs.
    """

    name: str
    from_table: str
    from_column: str
    to_table: str
    to_column: str
    join_type: str = Field(
        default="many_to_one",
        description="one_to_one | one_to_many | many_to_one | many_to_many",
    )
    description: Optional[str] = None
    tenant_id: str = "default"
    data_source_id: str = "default"

    # -- Provenance. A declared foreign key is a fact; a join inferred from
    #    column naming is a guess until somebody confirms it, and the two must
    #    not look alike to the model or to the join-path finder.
    origin: str = Field(
        default="declared",
        description="declared (a foreign key or curated relationship) | "
        "inferred (guessed by the scanner from column names and types)",
    )
    confidence: Optional[float] = Field(
        default=None,
        description="Inferred relationships only: 0-1, how sure the scanner is.",
    )
    review_status: str = Field(
        default="accepted",
        description="accepted | proposed | rejected. Declared relationships are "
        "accepted; inferred ones start proposed until an admin decides.",
    )

    @property
    def is_usable(self) -> bool:
        """Whether this edge may reach a prompt or a join path.

        Accepted edges always; rejected never; a proposed (unreviewed) inferred
        edge only when the scanner was confident -- a workspace whose database
        declares no foreign keys at all should not have to review every join
        before the agent can see any.
        """
        if self.review_status == "rejected":
            return False
        if self.review_status == "accepted":
            return True
        return (self.confidence or 0.0) >= INFERRED_MIN_CONFIDENCE

    @property
    def is_unconfirmed(self) -> bool:
        return self.origin == "inferred" and self.review_status != "accepted"

    def describe(self) -> str:
        line = (
            f"- {self.from_table}.{self.from_column} -> "
            f"{self.to_table}.{self.to_column} ({self.join_type})"
        )
        if self.is_unconfirmed:
            line += " [inferred from column names, not a declared foreign key]"
        if self.description:
            line += f" -- {self.description}"
        return line


#: Confidence at which an unreviewed inferred relationship is used anyway.
INFERRED_MIN_CONFIDENCE = 0.8


class SchemaContext(BaseModel):
    """Schema context selected for one question.

    ``strategy`` records how the content was chosen, which matters when
    diagnosing a bad answer: "search" means the model may simply never have
    been shown the right table.
    """

    strategy: str = Field(description="'full' | 'search' | 'empty'")
    text: str = Field(default="", description="Rendered schema text for the prompt")
    table_names: List[str] = Field(default_factory=list)
    char_count: int = 0
    total_tables: int = 0
    included_tables: int = 0
    bridge_tables: List[str] = Field(
        default_factory=list,
        description="Search strategy only: tables added because the join tree "
        "connecting the selected tables runs through them.",
    )
    hinted_tables: List[str] = Field(
        default_factory=list,
        description="Tables added because the question named a business term, "
        "metric or table linked to them.",
    )
    tables: List[TableMetadata] = Field(
        default_factory=list,
        exclude=True,
        description="The selected tables themselves, for callers that annotate "
        "the rendered text (core columns). Not serialized.",
    )

    @property
    def is_partial(self) -> bool:
        """True when the model was shown only part of the schema."""
        return self.strategy == "search"


class ScanReport(BaseModel):
    """Outcome of a scan."""

    tables_scanned: int = 0
    columns_profiled: int = 0
    categories_found: int = 0
    relationships_found: int = 0
    relationships_inferred: int = 0
    duration_ms: float = 0.0
    errors: List[str] = Field(default_factory=list)

    def summary(self) -> str:
        line = (
            f"Scanned {self.tables_scanned} tables, profiled "
            f"{self.columns_profiled} columns, found {self.categories_found} "
            f"enum-like columns and {self.relationships_found} relationships "
            f"in {self.duration_ms / 1000:.1f}s"
        )
        if self.relationships_inferred:
            line += f" ({self.relationships_inferred} of them inferred)"
        if self.errors:
            line += f" ({len(self.errors)} errors)"
        return line
