-- Generated by tools/export_sql_schema.py. Do not edit.
--
-- The control-plane schema: every migration this database has applied,
-- in order, followed by the ledger rows that record them -- so replaying
-- this file produces a database the migration runner considers current.
--
-- Rows are not here. See database/seed/ for the configuration and
-- reference data, which are the only rows safe to keep in the repository.

BEGIN;

-- ---- 0001_initial --------------------------------------------
-- Baseline: the control plane as it stood before migrations existed.
--
-- Carried over verbatim from the idempotent DDL blob in the original tenancy.py so
-- that an existing deployment can adopt migrations without a rebuild: every object
-- here is IF NOT EXISTS, so applying 0001 to a database that already has these
-- tables records the version and changes nothing.
--
-- Later migrations are NOT written this way. From 0002 on, each migration assumes
-- the state the previous one left.

CREATE SCHEMA IF NOT EXISTS vanna_app;

-- Needed for gen_random_uuid(). In PostgreSQL 13+ it is built in, but the
-- extension is still the portable way to be sure.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ----------------------------------------------------------------------
-- Tenants and membership
-- ----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vanna_app.tenants (
    id            text PRIMARY KEY,
    name          text        NOT NULL,
    description   text        NOT NULL DEFAULT '',
    -- NULL means "use the server default connection". Set per tenant to point a
    -- customer at their own database. Encrypted at rest from migration 0002.
    database_url  text,
    is_active     boolean     NOT NULL DEFAULT true,
    daily_quota   integer,
    max_rows      integer,
    -- Write statements for this workspace's admins. Off by default, and only half
    -- the decision: VANNA_ALLOW_WRITES must be set too.
    allow_writes  boolean     NOT NULL DEFAULT false,
    -- May members answer questions with their own LLM API key? Defaults to true
    -- because the alternative -- hitting a quota wall with no way past it -- is the
    -- situation the feature exists for.
    allow_byo_key boolean     NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Deployments that predate these columns.
ALTER TABLE vanna_app.tenants
    ADD COLUMN IF NOT EXISTS allow_writes boolean NOT NULL DEFAULT false;
ALTER TABLE vanna_app.tenants
    ADD COLUMN IF NOT EXISTS allow_byo_key boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS vanna_app.tenant_users (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    -- Always stored lowercased by the application, so the unique constraint below
    -- actually prevents Ada@x.com and ada@x.com being two members.
    email        text        NOT NULL,
    full_name    text        NOT NULL DEFAULT '',
    role         text        NOT NULL DEFAULT 'analyst',
    is_active    boolean     NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz,
    UNIQUE (tenant_id, email),
    CONSTRAINT tenant_users_role_check CHECK (role IN ('admin', 'analyst', 'viewer'))
);

CREATE INDEX IF NOT EXISTS tenant_users_email_idx ON vanna_app.tenant_users (email);

CREATE TABLE IF NOT EXISTS vanna_app.starter_questions (
    id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id  text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    question   text        NOT NULL,
    sort_order integer     NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------
-- Credentials
-- ----------------------------------------------------------------------

-- Identity is global; tenant_users remains the membership-and-role table, so one
-- account can belong to several workspaces with a different role in each.
CREATE TABLE IF NOT EXISTS vanna_app.users (
    email         text        PRIMARY KEY,
    password_hash text        NOT NULL,
    full_name     text        NOT NULL DEFAULT '',
    is_active     boolean     NOT NULL DEFAULT true,
    -- Forces a change on next login. Set when an admin issues a temporary password.
    must_change   boolean     NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

-- Sessions are keyed by the SHA-256 of the token, never the token. A dump of this
-- table therefore yields nothing replayable.
CREATE TABLE IF NOT EXISTS vanna_app.sessions (
    token_hash text        PRIMARY KEY,
    email      text        NOT NULL REFERENCES vanna_app.users(email) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    user_agent text        NOT NULL DEFAULT '',
    ip         text        NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS sessions_email_idx ON vanna_app.sessions (email);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON vanna_app.sessions (expires_at);

-- Machine credentials: the CLI and `vanna mcp`, which cannot hold a cookie.
-- Separate from sessions so revoking a laptop does not sign out a scheduled job.
CREATE TABLE IF NOT EXISTS vanna_app.api_tokens (
    token_hash   text        PRIMARY KEY,
    email        text        NOT NULL REFERENCES vanna_app.users(email) ON DELETE CASCADE,
    name         text        NOT NULL DEFAULT '',
    expires_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz
);

CREATE INDEX IF NOT EXISTS api_tokens_email_idx ON vanna_app.api_tokens (email);

-- ----------------------------------------------------------------------
-- Billing
-- ----------------------------------------------------------------------

-- Attached to the tenant rather than the user because the quota is enforced per
-- workspace. Rows accumulate: a renewal or plan change inserts, it does not update,
-- so the history reads correctly. The current subscription is the newest row.
CREATE TABLE IF NOT EXISTS vanna_app.subscriptions (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    -- Names a plan in vanna.core.billing.PLANS. Deliberately not a foreign key:
    -- plans are code constants that ship with a release.
    plan         text        NOT NULL DEFAULT 'free',
    status       text        NOT NULL DEFAULT 'active',
    starts_at    timestamptz NOT NULL DEFAULT now(),
    -- NULL means open-ended, which is how an enterprise agreement with no end date
    -- is expressed. An expired subscription falls back to free, never to zero.
    expires_at   timestamptz,
    cancelled_at timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS subscriptions_tenant_idx
    ON vanna_app.subscriptions (tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS vanna_app.payments (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    provider     text        NOT NULL DEFAULT 'manual',
    -- The provider's own identifier, and the reason this table is safe to write
    -- from a webhook: UNIQUE means a replayed delivery cannot bill twice.
    provider_ref text        NOT NULL UNIQUE,
    -- Integer cents. Money in a float is a rounding bug waiting for a large invoice.
    amount_cents integer     NOT NULL DEFAULT 0,
    currency     text        NOT NULL DEFAULT 'usd',
    status       text        NOT NULL DEFAULT 'succeeded',
    description  text        NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS payments_tenant_idx
    ON vanna_app.payments (tenant_id, created_at DESC);

-- ----------------------------------------------------------------------
-- Content
-- ----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vanna_app.conversations (
    id         text        PRIMARY KEY,
    tenant_id  text        NOT NULL,
    -- Owner. A conversation is one person's working notes, so it is scoped by user
    -- as well as tenant -- unlike saved queries and dashboards, which are
    -- deliberately shared across the workspace.
    user_id    text        NOT NULL,
    title      text        NOT NULL DEFAULT '',
    -- The whole Conversation model, messages included. Read and written as one unit
    -- by the agent on every turn, so a table per message would buy a join and cost
    -- write amplification.
    document   jsonb       NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS conversations_owner_idx
    ON vanna_app.conversations (tenant_id, user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS vanna_app.dashboards (
    id         text        PRIMARY KEY,
    tenant_id  text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    title      text        NOT NULL,
    document   jsonb       NOT NULL,
    created_by text        NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS dashboards_tenant_idx
    ON vanna_app.dashboards (tenant_id, title);

CREATE TABLE IF NOT EXISTS vanna_app.saved_queries (
    id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id  text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    created_by text        NOT NULL DEFAULT '',
    title      text        NOT NULL,
    question   text        NOT NULL DEFAULT '',
    sql        text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS saved_queries_tenant_idx
    ON vanna_app.saved_queries (tenant_id, created_at DESC);

-- ----------------------------------------------------------------------
-- Generation lineage
-- ----------------------------------------------------------------------

-- Not a foreign key to tenants. Generations are an audit trail: deleting a tenant
-- must not silently erase the record of what was asked under it. Deliberate
-- erasure is a separate, explicit operation.
CREATE TABLE IF NOT EXISTS vanna_app.generations (
    id                    text        PRIMARY KEY,
    tenant_id             text        NOT NULL,
    data_source_id        text        NOT NULL DEFAULT 'default',
    user_id               text        NOT NULL DEFAULT '',
    conversation_id       text        NOT NULL DEFAULT '',
    request_id            text        NOT NULL DEFAULT '',
    question              text        NOT NULL DEFAULT '',
    sql                   text        NOT NULL DEFAULT '',
    status                text        NOT NULL DEFAULT 'valid',
    error                 text,
    error_kind            text,
    row_count             integer,
    truncated             boolean     NOT NULL DEFAULT false,
    execution_ms          double precision,
    repair_attempts       integer     NOT NULL DEFAULT 0,
    model                 text,
    prompt_tokens         integer,
    completion_tokens     integer,
    cost_usd              double precision,
    retrieved_example_ids jsonb       NOT NULL DEFAULT '[]'::jsonb,
    retrieved_table_names jsonb       NOT NULL DEFAULT '[]'::jsonb,
    retrieval_strategy    text,
    feedback              text,
    feedback_comment      text,
    created_at            timestamptz NOT NULL DEFAULT now(),
    metadata              jsonb       NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS generations_tenant_created_idx
    ON vanna_app.generations (tenant_id, created_at DESC);
-- Feedback arrives keyed by request_id, well after the row was written.
CREATE INDEX IF NOT EXISTS generations_request_idx
    ON vanna_app.generations (tenant_id, request_id);

-- ---- 0002_auth_hardening -------------------------------------
-- Session scoping, external identity, and self-service password reset.
--
-- Three gaps this closes.
--
-- `must_change` was advisory. The API issued a full 72-hour session and only the
-- browser honoured the flag, so a temporary password was in practice a permanent
-- credential for anything that spoke HTTP. `sessions.scope` makes the restriction
-- something the server enforces: a session issued for a must-change account can
-- reach the password endpoint and nothing else.
--
-- `users` assumed a password existed. An OIDC account has none, and a row with an
-- empty `password_hash` would silently accept `verify_password('', '')` if that
-- function ever grew laxer. `auth_provider` states the intent instead of inferring
-- it from an empty column.
--
-- There was no way to recover an account. `password_resets` holds hashed,
-- single-use, short-lived tokens -- the same treatment sessions get, for the same
-- reason: a dump of this table must not be replayable.

-- ----------------------------------------------------------------------
-- Session scope
-- ----------------------------------------------------------------------

ALTER TABLE vanna_app.sessions
    ADD COLUMN IF NOT EXISTS scope text NOT NULL DEFAULT 'full';

ALTER TABLE vanna_app.sessions
    DROP CONSTRAINT IF EXISTS sessions_scope_check;

ALTER TABLE vanna_app.sessions
    ADD CONSTRAINT sessions_scope_check
    CHECK (scope IN ('full', 'password_change_only'));

-- ----------------------------------------------------------------------
-- Where an identity comes from
-- ----------------------------------------------------------------------

ALTER TABLE vanna_app.users
    ADD COLUMN IF NOT EXISTS auth_provider text NOT NULL DEFAULT 'password';

ALTER TABLE vanna_app.users
    ADD COLUMN IF NOT EXISTS external_id text;

ALTER TABLE vanna_app.users
    ADD COLUMN IF NOT EXISTS password_changed_at timestamptz;

-- Backfill: everything that exists today was created with a password.
UPDATE vanna_app.users
   SET password_changed_at = created_at
 WHERE password_changed_at IS NULL;

CREATE INDEX IF NOT EXISTS users_external_idx
    ON vanna_app.users (auth_provider, external_id);

-- ----------------------------------------------------------------------
-- Password reset
-- ----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vanna_app.password_resets (
    token_hash text        PRIMARY KEY,
    email      text        NOT NULL REFERENCES vanna_app.users(email) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    -- Single use. Set on redemption rather than deleting the row, so a second
    -- attempt with the same link can be distinguished from an unknown one in the
    -- logs -- without telling the caller which it was.
    used_at    timestamptz,
    requested_ip text      NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS password_resets_email_idx
    ON vanna_app.password_resets (email);
CREATE INDEX IF NOT EXISTS password_resets_expiry_idx
    ON vanna_app.password_resets (expires_at);

-- ----------------------------------------------------------------------
-- Datasource credentials at rest
-- ----------------------------------------------------------------------

-- The application seals `database_url` with Fernet from this release on. Existing
-- rows stay readable (the reader passes through anything without the `enc:v1:`
-- marker) and are re-written sealed the next time the workspace is saved.
--
-- Deliberately not re-encrypted here: this migration has no access to
-- VANNA_SECRET_KEY, and a migration that silently no-ops when a key is absent is
-- worse than one that never claimed to do the work. `vanna-app seal-secrets`
-- performs the backfill with the key in hand.
COMMENT ON COLUMN vanna_app.tenants.database_url IS
    'Connection URL. Sealed with Fernet under VANNA_SECRET_KEY; values prefixed '
    'enc:v1: are ciphertext. Legacy plaintext rows are still readable.';

-- ---- 0003_counters -------------------------------------------
-- Shared counters for quota, rate limiting and login throttling.
--
-- All three used to be Python dictionaries. That has two consequences and both are
-- worse than they sound.
--
-- The limits multiply by the worker count. Two uvicorn workers enforcing "200 per
-- day" independently permit 400, and nobody can tell from the outside which number
-- is real. In practice this pinned the deployment to a single worker -- the entire
-- horizontal-scaling story, given up to avoid one table.
--
-- The login throttle was also unbounded: `defaultdict(deque)` keyed by address and
-- IP, with entries created on every attempt and removed only on success. Spraying
-- addresses grew it forever.
--
-- A fixed window is deliberate rather than a sliding one. A sliding window needs
-- the individual event timestamps, which is a row per request; a fixed window is
-- one row per (key, window) and a single atomic UPSERT. The cost is a boundary
-- effect -- up to 2x the limit across a window edge -- which is acceptable for a
-- daily quota and a per-minute burst guard, and is not acceptable for the login
-- throttle, so that one uses a short window where the effect is small.

CREATE TABLE IF NOT EXISTS vanna_app.counters (
    -- 'quota:tenant:acme' | 'rate:acme:ada@example.com' | 'login:ip:203.0.113.4'
    bucket_key   text        NOT NULL,
    -- Start of the fixed window this row counts, truncated by the caller so every
    -- process agrees on the boundary without coordinating.
    window_start timestamptz NOT NULL,
    count        integer     NOT NULL DEFAULT 0,
    updated_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (bucket_key, window_start)
);

-- Garbage collection reads by age across all keys.
CREATE INDEX IF NOT EXISTS counters_window_idx
    ON vanna_app.counters (window_start);

-- ---- 0004_audit ----------------------------------------------
-- Audit trails: agent events, and administrative actions.
--
-- The library already defines an AuditLogger interface and the Agent constructor
-- already accepts one. Nothing ever passed an implementation, so every tool
-- invocation and access decision was unrecorded.
--
-- Administrative actions were worse: repointing a workspace at a different
-- database, granting someone admin, changing a plan, resetting a password -- all
-- existed only as lines on stdout. "Who changed this, and when" is the first
-- question asked after an incident and the logs are the wrong place to answer it,
-- because they are not queryable, not retained, and not scoped to a tenant.
--
-- Two tables rather than one. Agent events are high-volume, machine-shaped, and
-- interesting in aggregate. Admin events are rare, human-shaped, and interesting
-- individually -- and they must be readable by a tenant admin looking at their own
-- workspace, which agent-level tool traces should not be.

-- ----------------------------------------------------------------------
-- Agent events
-- ----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vanna_app.audit_events (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id        text        NOT NULL,
    event_type      text        NOT NULL,
    tenant_id       text        NOT NULL DEFAULT '',
    user_id         text        NOT NULL DEFAULT '',
    user_email      text        NOT NULL DEFAULT '',
    conversation_id text        NOT NULL DEFAULT '',
    request_id      text        NOT NULL DEFAULT '',
    tool_name       text,
    access_granted  boolean,
    payload         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_events_tenant_idx
    ON vanna_app.audit_events (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS audit_events_request_idx
    ON vanna_app.audit_events (request_id);
-- Denials are what anyone actually goes looking for. A partial index keeps that
-- lookup cheap without paying for an index over the (much larger) success case.
CREATE INDEX IF NOT EXISTS audit_events_denied_idx
    ON vanna_app.audit_events (tenant_id, created_at DESC)
    WHERE access_granted = false;

-- ----------------------------------------------------------------------
-- Administrative actions
-- ----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vanna_app.admin_audit (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Who did it. Email rather than a foreign key: the record must survive the
    -- deletion of the account that made the change, which is exactly the case
    -- somebody will be investigating.
    actor_email  text        NOT NULL,
    actor_ip     text        NOT NULL DEFAULT '',
    -- 'tenant.update' | 'member.role_change' | 'billing.plan' | 'account.reset' ...
    action       text        NOT NULL,
    -- What it was done to. Tenant id where there is one, so a workspace admin can
    -- be shown their own workspace's history and nothing else.
    tenant_id    text        NOT NULL DEFAULT '',
    target       text        NOT NULL DEFAULT '',
    -- Before/after for the fields that changed. Credentials are redacted by the
    -- writer -- see record_admin_action -- so this column never holds a password.
    details      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    request_id   text        NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_audit_tenant_idx
    ON vanna_app.admin_audit (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_actor_idx
    ON vanna_app.admin_audit (actor_email, created_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_action_idx
    ON vanna_app.admin_audit (action, created_at DESC);

-- ---- 0005_search_and_cost ------------------------------------
-- Make history search and cost reporting survive a real amount of data.
--
-- The history view filters with `question ILIKE '%…%' OR sql ILIKE '%…%'` against
-- a table indexed only by (tenant_id, created_at). Neither predicate can use that
-- index, so every search was a sequential scan over the fastest-growing table in
-- the system -- fine on a demo, quadratically worse every month in production.
--
-- pg_trgm rather than a tsvector column. Full-text search stems and tokenises,
-- which is right for prose and wrong here: people search history for fragments of
-- SQL and half-remembered column names, and `WHERE amount_cents` is not a word.
-- Trigram indexes accelerate exactly the LIKE pattern already being used, so the
-- query does not change -- only its plan does.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX IF NOT EXISTS generations_question_trgm_idx
    ON vanna_app.generations USING gin (question gin_trgm_ops);

CREATE INDEX IF NOT EXISTS generations_sql_trgm_idx
    ON vanna_app.generations USING gin (sql gin_trgm_ops);

-- The "mine" filter on the history view, and per-user cost attribution.
CREATE INDEX IF NOT EXISTS generations_user_idx
    ON vanna_app.generations (tenant_id, user_id, created_at DESC);

-- Cost rollups scan a date range for one tenant and sum. The existing
-- (tenant_id, created_at DESC) index serves the range; including the payload
-- columns lets the rollup answer from the index alone.
CREATE INDEX IF NOT EXISTS generations_cost_idx
    ON vanna_app.generations (tenant_id, created_at)
    INCLUDE (cost_usd, prompt_tokens, completion_tokens, model);

-- Retention deletes by age across every tenant.
CREATE INDEX IF NOT EXISTS generations_created_idx
    ON vanna_app.generations (created_at);

-- ---- 0006_grants ---------------------------------------------
-- Per-table and per-column grants: the authorization surface writes are checked against.
--
-- Until now a workspace's `allow_writes` flag was the whole permission model: on, and
-- an admin could change anything the connection string reached. That is a switch, not a
-- permission -- there was no way to say "this agent may update order status and nothing
-- else", which is the only shape of write access anyone actually wants to grant.
--
-- Two tables rather than one, because the questions differ. A table grant answers "may
-- this role touch this relation, and with which verb". A column grant answers "may this
-- role read, filter on, aggregate, or assign this field". Collapsing them would force
-- every column to inherit its table's verbs, and the common case -- readable table, two
-- writable columns -- would become inexpressible.
--
-- The CHECK constraints restate an invariant the Pydantic models also enforce: a write
-- flag requires its read flag. The duplication is deliberate. The models guard the API,
-- the constraints guard everything else -- a migration, a psql session, a future store
-- implementation -- and the invariant is one nobody should be able to break by taking a
-- different path to the same row.

CREATE TABLE IF NOT EXISTS vanna_app.table_grants (
    tenant_id       text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id  text        NOT NULL,
    -- Matches an entry in the caller's group memberships. A caller holding several
    -- roles receives the union of their grants, so adding a role can only widen.
    role            text        NOT NULL,
    -- Normalized (casefolded, unquoted) name -- the key a write plan is matched on.
    table_key       text        NOT NULL,
    -- The same name as an administrator typed it, kept only so an admin screen can
    -- show `Sales.Orders` rather than `sales.orders`.
    table_name      text        NOT NULL,

    can_select      boolean     NOT NULL DEFAULT false,
    can_insert      boolean     NOT NULL DEFAULT false,
    can_update      boolean     NOT NULL DEFAULT false,
    can_delete      boolean     NOT NULL DEFAULT false,

    granted_by      text,
    updated_at      timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id, role, table_key),

    CONSTRAINT table_grants_insert_requires_select CHECK (NOT can_insert OR can_select),
    CONSTRAINT table_grants_update_requires_select CHECK (NOT can_update OR can_select),
    CONSTRAINT table_grants_delete_requires_select CHECK (NOT can_delete OR can_select)
);

CREATE TABLE IF NOT EXISTS vanna_app.column_grants (
    tenant_id       text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id  text        NOT NULL,
    role            text        NOT NULL,
    table_key       text        NOT NULL,
    column_key      text        NOT NULL,
    table_name      text        NOT NULL,
    column_name     text        NOT NULL,

    can_read        boolean     NOT NULL DEFAULT false,
    -- Separate from can_read because they leak differently: a column you may filter on
    -- but not read still answers questions about individual rows, one predicate at a time.
    can_filter      boolean     NOT NULL DEFAULT false,
    can_aggregate   boolean     NOT NULL DEFAULT false,
    can_write       boolean     NOT NULL DEFAULT false,

    granted_by      text,
    updated_at      timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id, role, table_key, column_key),

    CONSTRAINT column_grants_filter_requires_read    CHECK (NOT can_filter    OR can_read),
    CONSTRAINT column_grants_aggregate_requires_read CHECK (NOT can_aggregate OR can_read),
    CONSTRAINT column_grants_write_requires_read     CHECK (NOT can_write     OR can_read)
);

-- Resolution reads every grant for one (tenant, data source) at once.
CREATE INDEX IF NOT EXISTS column_grants_lookup_idx
    ON vanna_app.column_grants (tenant_id, data_source_id, table_key);

-- The version a write is approved under.
--
-- A write is authorized once when it is proposed and again when it executes, and those
-- are separated by however long a human takes to read an approval card. Without a
-- number to compare, a grant revoked in between would be revoked in name only: the
-- approved plan would still carry permissions that no longer exist. Every mutation
-- above bumps this in the same transaction, so a reader can never see a changed grant
-- under an unchanged version.
CREATE TABLE IF NOT EXISTS vanna_app.grant_versions (
    tenant_id       text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id  text        NOT NULL,
    version         bigint      NOT NULL DEFAULT 1,
    updated_at      timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id),

    -- 0 means "never granted anything", which resolution reports without a row here.
    -- A stored version is therefore always a real change.
    CONSTRAINT grant_versions_positive CHECK (version > 0)
);

-- ---- 0007_write_approvals ------------------------------------
-- Writes awaiting a decision, and who has to make it.
--
-- Approval spans requests. A change is proposed in one turn, read and decided in
-- another, and the two may be minutes and several HTTP requests apart. The previous
-- attempt kept the pending write in `ToolContext.metadata`, which lives for exactly
-- one request -- so the approval could never arrive, and on a write-enabled workspace
-- every statement previewed forever and none ever ran. This table is the fix.
--
-- Note what is stored in its own column rather than folded into `plan_hash`:
-- `grants_version`, `catalog_fingerprint` and `expires_at`. The hash proves the
-- statement is the one that was shown. These prove the *world* it was shown in still
-- holds. Keeping them apart is what lets a refusal say which one moved -- "permissions
-- changed" is something a person can act on, "something changed" is not.
--
-- `plan` is the typed WritePlan, not SQL. It is re-parsed through its Pydantic model
-- and re-validated against freshly built permissions before it runs, so a row edited
-- here cannot skip a validator. The stored statements are rebuilt and compared, never
-- executed as stored.

ALTER TABLE vanna_app.tenants
    ADD COLUMN IF NOT EXISTS write_approval_mode text NOT NULL DEFAULT 'self';

DO $$
BEGIN
    ALTER TABLE vanna_app.tenants
        ADD CONSTRAINT tenants_write_approval_mode_check
        CHECK (write_approval_mode IN
               ('self', 'second_person_destructive', 'second_person_always'));
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS vanna_app.pending_writes (
    id                  uuid        PRIMARY KEY,
    tenant_id           text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id      text        NOT NULL,

    conversation_id     text,
    request_id          text,
    requested_by        text        NOT NULL,
    requested_by_email  text,

    status              text        NOT NULL DEFAULT 'pending',

    -- The typed plan. Never trusted as stored: re-parsed and re-validated first.
    plan                jsonb       NOT NULL,
    -- The statements as they will run, still parameterized. Safe to keep and to
    -- show, because the markers stand where the tenant's data would be.
    statement_preview   text        NOT NULL,
    -- Shapes only: counts, tables, verbs. Never the bound values.
    parameter_summary   jsonb       NOT NULL DEFAULT '{}'::jsonb,

    operation           text        NOT NULL,
    tables              jsonb       NOT NULL DEFAULT '[]'::jsonb,
    expected_row_count  integer     NOT NULL DEFAULT 0,
    is_destructive      boolean     NOT NULL DEFAULT false,

    -- Each independently checkable, so a refusal can name what moved.
    plan_hash           text        NOT NULL,
    grants_version      bigint      NOT NULL DEFAULT 0,
    catalog_fingerprint text,

    expires_at          timestamptz NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    decided_by          text,
    decided_at          timestamptz,
    error               text,

    CONSTRAINT pending_writes_status_check CHECK (status IN (
        'pending', 'awaiting_review', 'approved', 'rejected',
        'expired', 'refused', 'executed', 'failed')),

    CONSTRAINT pending_writes_plan_hash_check CHECK (plan_hash ~ '^sha256:[0-9a-f]{64}$'),
    CONSTRAINT pending_writes_rows_check CHECK (expected_row_count >= 0),

    -- A decided row must record who decided it, and an undecided one must not
    -- claim it was. Expired is the exception: nobody decided it, time did.
    CONSTRAINT pending_writes_decision_consistency CHECK (
        (status IN ('pending', 'awaiting_review')
            AND decided_by IS NULL AND decided_at IS NULL)
        OR (status = 'expired' AND decided_by IS NULL)
        OR (status IN ('approved', 'rejected', 'refused', 'executed', 'failed')
            AND decided_by IS NOT NULL AND decided_at IS NOT NULL)
    )
);

-- The review queue, and the expiry sweep. Partial because the settled rows are
-- the overwhelming majority and neither query ever wants them.
CREATE INDEX IF NOT EXISTS pending_writes_open_idx
    ON vanna_app.pending_writes (tenant_id, status, expires_at)
    WHERE status IN ('pending', 'awaiting_review');

-- "What did this workspace change, and who approved it."
CREATE INDEX IF NOT EXISTS pending_writes_history_idx
    ON vanna_app.pending_writes (tenant_id, created_at DESC);

-- ---- 0008_instructions ---------------------------------------
-- Business rules move from the filesystem into the control plane.
--
-- They lived as `knowledge/<tenant>/rules/*.md`, one file per rule named after a
-- slug of its own text. That naming carried two bugs a year of use would find:
-- two rules sharing their first sixty characters resolved to the same filename
-- and the second silently destroyed the first, and editing a rule's wording
-- moved it to a new file and orphaned the old one, so the rule appeared twice.
-- Identity here is a uuid, so neither is expressible.
--
-- It also puts rules where the rest of a workspace's state already is: covered by
-- the same backup, deleted by the same purge, and readable by every replica
-- rather than by whichever ones share a volume.
--
-- The platform baseline is deliberately NOT rows in this table. It lives in
-- instructions/baseline.yml and is merged at read time, so editing it reaches
-- every workspace on deploy instead of needing a backfill -- and so that no
-- DELETE, however privileged, can remove a rule the platform owns.

CREATE TABLE IF NOT EXISTS vanna_app.instructions (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    text        text        NOT NULL,
    scope       text        NOT NULL DEFAULT 'global',
    scope_ref   text,
    priority    integer     NOT NULL DEFAULT 0,
    enabled     boolean     NOT NULL DEFAULT true,

    -- 'tenant' was written here; 'library' was copied from a starter pack and is
    -- owned by the workspace from that moment. 'platform' is absent on purpose:
    -- a platform rule is never a row.
    origin      text        NOT NULL DEFAULT 'tenant',
    source_pack text,

    metadata    jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at  timestamptz NOT NULL DEFAULT now(),
    created_by  text,
    updated_at  timestamptz NOT NULL DEFAULT now(),
    updated_by  text,

    CONSTRAINT instructions_scope_check
        CHECK (scope IN ('global', 'data_source', 'table', 'group')),
    CONSTRAINT instructions_origin_check
        CHECK (origin IN ('tenant', 'library')),
    CONSTRAINT instructions_text_check
        CHECK (length(btrim(text)) > 0),
    -- The invariant the stores also enforce in Python, restated where no code
    -- path can go around it. A non-global scope with no reference applies to
    -- nothing, and is indistinguishable from a rule that was silently dropped.
    CONSTRAINT instructions_scope_ref_check CHECK (
        scope = 'global' OR (scope_ref IS NOT NULL AND length(btrim(scope_ref)) > 0))
);

-- Resolution reads one tenant's rules in priority order, every request.
CREATE INDEX IF NOT EXISTS instructions_tenant_idx
    ON vanna_app.instructions (tenant_id, priority DESC, created_at);

-- Which platform rules a workspace has switched off.
--
-- Only the exceptions are stored. Absence means "on", which is what lets a newly
-- shipped baseline rule apply everywhere the moment it deploys rather than
-- needing a row written per workspace first.
CREATE TABLE IF NOT EXISTS vanna_app.instruction_overrides (
    tenant_id   text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    baseline_id text        NOT NULL,
    disabled    boolean     NOT NULL DEFAULT true,
    updated_at  timestamptz NOT NULL DEFAULT now(),
    updated_by  text,
    PRIMARY KEY (tenant_id, baseline_id)
);

-- Which starter packs a workspace has taken, so enabling one twice is a no-op
-- rather than a second copy of every rule in it.
CREATE TABLE IF NOT EXISTS vanna_app.instruction_packs_enabled (
    tenant_id  text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    pack_id    text        NOT NULL,
    enabled_at timestamptz NOT NULL DEFAULT now(),
    enabled_by text,
    PRIMARY KEY (tenant_id, pack_id)
);

-- Set once, by the one-shot markdown import.
--
-- Load-bearing, not bookkeeping. The obvious import rule -- "bring the files in
-- when the table is empty" -- resurrects every rule an administrator
-- deliberately deleted, on the next restart. `_seed_knowledge` already carries a
-- comment about exactly that failure for examples; this is how instructions
-- avoid it.
ALTER TABLE vanna_app.tenants
    ADD COLUMN IF NOT EXISTS instructions_imported_at timestamptz;

-- ---- 0009_grant_defaults -------------------------------------
-- Grant defaults: what a workspace grants before anybody edits the matrix.
--
-- Until now a new workspace granted nothing, with no screen on which to change
-- that, so the permission model was theoretically complete and practically
-- unreachable. Two things fix that: a preset that fills in a sensible starting
-- matrix, and a per-workspace record of which preset that was.

-- Where a grant row came from.
--
-- The reason a preset can be re-applied at all. Without it, "re-apply" either
-- discards an administrator's own edits or cannot discard anything, and neither
-- is usable. 'explicit' is the default precisely so that every row written before
-- this migration is protected: a later `replace` deletes only what a preset wrote.
ALTER TABLE vanna_app.table_grants
    ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'explicit';
ALTER TABLE vanna_app.column_grants
    ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'explicit';

DO $$ BEGIN
    ALTER TABLE vanna_app.table_grants
        ADD CONSTRAINT table_grants_source_check
        CHECK (source IN ('explicit', 'preset'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE vanna_app.column_grants
        ADD CONSTRAINT column_grants_source_check
        CHECK (source IN ('explicit', 'preset'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Preset rows are rewritten as a set, which is the only reason the filter above
-- has to be fast.
CREATE INDEX IF NOT EXISTS table_grants_source_idx
    ON vanna_app.table_grants (tenant_id, data_source_id, role)
    WHERE source = 'preset';
CREATE INDEX IF NOT EXISTS column_grants_source_idx
    ON vanna_app.column_grants (tenant_id, data_source_id, role)
    WHERE source = 'preset';

-- What a workspace grants by default, per role, per connection.
--
-- Intent, not permission. Nothing in this table is consulted when a caller's
-- access is resolved: applying a policy writes ordinary rows into `table_grants`
-- and `column_grants`, and those are what resolution reads.
--
-- That indirection is the design, not an implementation detail. It keeps the
-- fail-closed rule intact -- a column with no row is dropped, with no second code
-- path that could disagree -- it means every change still moves `grant_versions`,
-- so a write approved under the old policy is re-authorized before it runs, and
-- it means the matrix an administrator reads is the same set of rows the resolver
-- reads, with no "effective versus stored" distinction to explain.
--
-- Keyed on the data source as well as the tenant because a workspace can be
-- repointed at a different database, and a policy written for one schema must not
-- follow it to another.
CREATE TABLE IF NOT EXISTS vanna_app.grant_policies (
    tenant_id            text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id       text        NOT NULL,
    role                 text        NOT NULL,

    -- 'none' is the default, and means today's behaviour: nothing is granted
    -- until somebody grants it. Not constrained to a list here, because a
    -- deployment may register its own preset; the API validates the name against
    -- what is actually registered.
    preset               text        NOT NULL DEFAULT 'none',

    -- Whether a table a later scan discovers is granted automatically. Off by
    -- default: a table that has just appeared is one nobody has looked at yet.
    apply_to_new_tables  boolean     NOT NULL DEFAULT false,

    -- Whether these grants also decide what may be *read*.
    --
    -- Off by default, and it must stay that way for an existing deployment.
    -- Until now grants governed writes only, so switching this on for a
    -- workspace with an empty matrix would deny every table at once. The API
    -- refuses to enable it before the role has grants.
    enforce_reads        boolean     NOT NULL DEFAULT false,

    last_applied_at      timestamptz,
    last_applied_version bigint,
    updated_by           text,
    updated_at           timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id, role)
);

-- ---- 0010_schema_catalog -------------------------------------
-- The schema catalog, made durable and queryable.
--
-- Until now the catalog lived in one JSON file on disk ($VANNA_DATA_DIR/catalog.json),
-- keyed in memory by (tenant, data source). That is fine for a laptop and wrong for a
-- deployment: there is no row-level tenant isolation, two replicas cannot both own the
-- file, and an administrator cannot query it. This migration gives the catalog the same
-- treatment every other piece of shared state already has.
--
-- The organising idea is a split this codebase already discovered once, in
-- capabilities/schema_catalog/dbt.py: "dbt owns meaning (descriptions), the scan owns
-- structure (real types, nullability, row counts, observed values). Taking whole records
-- from either side would throw away half the picture."
--
-- So structure and meaning live in different tables:
--
--   catalog_tables / catalog_columns / catalog_relationships
--       Machine-discovered. Every scan rewrites them.
--   table_annotations / column_annotations / business_domains / domain_tables
--       Human-authored. No scan ever touches them.
--
-- That is not tidiness, it is the fix for a real defect. `upsert_tables` replaces a
-- whole TableMetadata record, so with meaning stored alongside structure a routine
-- re-scan silently destroys every description somebody wrote. Separate tables make that
-- impossible rather than merely discouraged.
--
-- Everything is keyed on the normalized name -- `table_key`, `column_key`, produced by
-- normalize_table/normalize_identifier in core/grants/models.py -- and not on a
-- surrogate row id. That is deliberate, and is where this diverges from the reference
-- implementation, which needs version-stable resource ids because its grants carry a
-- foreign key to them. Ours do not: table_grants and column_grants are already keyed
-- (tenant_id, data_source_id, role, table_key[, column_key]). Keying the catalog the
-- same way means a grant, an annotation and a scanned column all join on the same
-- columns, and a grant survives a re-scan for free rather than by careful bookkeeping.

-- ----------------------------------------------------------------------
-- Structure: what the database actually contains
-- ----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vanna_app.catalog_tables (
    tenant_id           text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id      text        NOT NULL,
    -- Normalized (casefolded, unquoted), schema-qualified where the engine has schemas.
    -- The same key the grant tables use.
    table_key           text        NOT NULL,

    -- As the database spells it, so a screen can show `Sales.Orders`.
    schema_name         text        NOT NULL DEFAULT '',
    table_name          text        NOT NULL,
    table_type          text        NOT NULL DEFAULT 'table',
    row_count_estimate  bigint,

    -- Freshness, and why a table has no columns.
    --
    -- Not decorative: the scanner records a table it failed to profile with
    -- status='failed', an error message and an empty column list. Flattening that to
    -- 'scanned' would present a successfully-scanned table that happens to have no
    -- columns -- and grant resolution drops zero-column tables, so the failure would
    -- turn into a silent disappearance instead of something a screen can report.
    status              text        NOT NULL DEFAULT 'scanned',
    error_message       text,

    -- A table that vanished from a scan becomes 'removed' rather than being deleted.
    -- Deleting it would take its annotations and its domain membership with it, and a
    -- table can disappear for reasons that are not permanent -- a failed deploy, a
    -- rename in progress, a scan that ran against a replica mid-migration. Recording
    -- the absence keeps the curation and lets a screen say "this is gone" honestly.
    lifecycle_status    text        NOT NULL DEFAULT 'present',

    first_seen_at       timestamptz NOT NULL DEFAULT now(),
    last_seen_at        timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id, table_key),

    CONSTRAINT catalog_tables_lifecycle_check
        CHECK (lifecycle_status IN ('present', 'removed')),
    CONSTRAINT catalog_tables_type_check
        CHECK (table_type IN ('table', 'view', 'materialized_view')),
    -- Mirrors CatalogStatus in capabilities/schema_catalog/models.py.
    CONSTRAINT catalog_tables_status_check
        CHECK (status IN ('not_scanned', 'scanning', 'scanned', 'stale', 'failed'))
);

CREATE TABLE IF NOT EXISTS vanna_app.catalog_columns (
    tenant_id           text        NOT NULL,
    data_source_id      text        NOT NULL,
    table_key           text        NOT NULL,
    column_key          text        NOT NULL,

    column_name         text        NOT NULL,
    ordinal             integer     NOT NULL DEFAULT 0,
    data_type           text        NOT NULL DEFAULT 'unknown',
    nullable            boolean     NOT NULL DEFAULT true,
    is_primary_key      boolean     NOT NULL DEFAULT false,
    -- Identity/computed. The database refuses an INSERT that names one, which is why
    -- grant resolution never marks such a column writable.
    is_generated        boolean     NOT NULL DEFAULT false,
    has_default         boolean     NOT NULL DEFAULT false,

    -- Profiling output. Worth persisting: re-deriving it costs a SELECT DISTINCT per
    -- column against the customer's warehouse.
    low_cardinality     boolean     NOT NULL DEFAULT false,
    categories          jsonb       NOT NULL DEFAULT '[]'::jsonb,
    sample_values       jsonb       NOT NULL DEFAULT '[]'::jsonb,
    foreign_key         jsonb,

    lifecycle_status    text        NOT NULL DEFAULT 'present',
    first_seen_at       timestamptz NOT NULL DEFAULT now(),
    last_seen_at        timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id, table_key, column_key),

    -- Cascades from its table, which is safe because a table is only ever marked
    -- 'removed', never deleted, by a scan.
    FOREIGN KEY (tenant_id, data_source_id, table_key)
        REFERENCES vanna_app.catalog_tables (tenant_id, data_source_id, table_key)
        ON DELETE CASCADE,

    CONSTRAINT catalog_columns_lifecycle_check
        CHECK (lifecycle_status IN ('present', 'removed'))
);

-- Building the prompt reads every column of a data source at once.
CREATE INDEX IF NOT EXISTS catalog_columns_lookup_idx
    ON vanna_app.catalog_columns (tenant_id, data_source_id, table_key);

CREATE TABLE IF NOT EXISTS vanna_app.catalog_relationships (
    tenant_id           text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id      text        NOT NULL,

    from_table_key      text        NOT NULL,
    from_column_key     text        NOT NULL,
    to_table_key        text        NOT NULL,
    to_column_key       text        NOT NULL,

    -- Mirrors RelationshipMetadata. `name` and `description` are what reach the
    -- prompt; `join_type` is what stops the model fanning out a one-to-many join
    -- and double-counting a sum.
    name                text        NOT NULL DEFAULT '',
    join_type           text        NOT NULL DEFAULT 'many_to_one',
    description         text,

    lifecycle_status    text        NOT NULL DEFAULT 'present',
    first_seen_at       timestamptz NOT NULL DEFAULT now(),
    last_seen_at        timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id, from_table_key, from_column_key,
                 to_table_key, to_column_key),

    CONSTRAINT catalog_relationships_join_type_check
        CHECK (join_type IN ('one_to_one', 'one_to_many', 'many_to_one', 'many_to_many')),
    CONSTRAINT catalog_relationships_lifecycle_check
        CHECK (lifecycle_status IN ('present', 'removed'))
);

-- ----------------------------------------------------------------------
-- Meaning: what it is for
-- ----------------------------------------------------------------------
--
-- Deliberately not foreign-keyed to catalog_tables. An annotation must outlive
-- structural churn -- that is the whole reason it is a separate table -- so it is tied
-- to the tenant and nothing else. An annotation for a table that no longer exists is
-- harmless, and is exactly what you want back if the table returns.

CREATE TABLE IF NOT EXISTS vanna_app.table_annotations (
    tenant_id       text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id  text        NOT NULL,
    table_key       text        NOT NULL,

    display_name    text        NOT NULL DEFAULT '',
    -- Reaches the model verbatim. Worth more to generation accuracy than the type is.
    description     text        NOT NULL DEFAULT '',
    domain_id       uuid,

    updated_by      text,
    updated_at      timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id, table_key)
);

CREATE TABLE IF NOT EXISTS vanna_app.column_annotations (
    tenant_id       text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id  text        NOT NULL,
    table_key       text        NOT NULL,
    column_key      text        NOT NULL,

    display_name    text        NOT NULL DEFAULT '',
    description     text        NOT NULL DEFAULT '',

    -- {"A": "Active", "C": "Cancelled"} -- what a coded value means. The single
    -- highest-value piece of column metadata for text-to-SQL: without it the model
    -- guesses the literal, and a wrong literal returns zero rows rather than an error.
    value_labels    jsonb       NOT NULL DEFAULT '{}'::jsonb,

    -- Curated counterpart to the scanner's SENSITIVE_COLUMN_PATTERNS regex. The regex
    -- decides what to redact from a prompt automatically; this records a human's
    -- judgement, which a screen can surface when somebody is about to grant read.
    sensitivity     text,

    updated_by      text,
    updated_at      timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id, table_key, column_key),

    CONSTRAINT column_annotations_sensitivity_check
        CHECK (sensitivity IS NULL
               OR sensitivity IN ('public', 'internal', 'confidential', 'restricted'))
);

-- ----------------------------------------------------------------------
-- Business domains
-- ----------------------------------------------------------------------
--
-- A named slice of one database, with the vocabulary people use to talk about it.
--
-- Note what this is not: it is not an access control. Domain membership is intersected
-- with what the caller may already read, so a domain can only ever narrow the tables in
-- play, never add one. A grouping that could widen access would be a second, weaker
-- permission system wearing a friendly name.
--
-- Per (tenant, data source) rather than per tenant, because a domain names tables and
-- tables belong to one database.

CREATE TABLE IF NOT EXISTS vanna_app.business_domains (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id  text        NOT NULL,

    name            text        NOT NULL,
    description     text        NOT NULL DEFAULT '',

    -- {"churn": "a customer with no order in 90 days"} -- the terms of art that the
    -- schema alone cannot tell you.
    terminology     jsonb       NOT NULL DEFAULT '{}'::jsonb,

    is_enabled      boolean     NOT NULL DEFAULT true,

    created_by      text,
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Case-insensitive, because "Sales" and "sales" are the same domain to everyone except
-- a database.
CREATE UNIQUE INDEX IF NOT EXISTS business_domains_name_idx
    ON vanna_app.business_domains (tenant_id, data_source_id, lower(name));

CREATE TABLE IF NOT EXISTS vanna_app.domain_tables (
    tenant_id       text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    domain_id       uuid        NOT NULL REFERENCES vanna_app.business_domains(id) ON DELETE CASCADE,
    -- Same key as everywhere else, so membership joins to grants and to the catalog
    -- without a lookup table.
    table_key       text        NOT NULL,

    added_by        text,
    added_at        timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, domain_id, table_key)
);

CREATE INDEX IF NOT EXISTS domain_tables_by_table_idx
    ON vanna_app.domain_tables (tenant_id, table_key);

-- Added after business_domains exists, so the reference is real rather than advisory.
-- ON DELETE SET NULL: deleting a domain must not delete the table's description.
DO $$ BEGIN
    ALTER TABLE vanna_app.table_annotations
        ADD CONSTRAINT table_annotations_domain_fk
        FOREIGN KEY (domain_id) REFERENCES vanna_app.business_domains(id)
        ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---- 0011_workspace_datasources ------------------------------
-- More than one database per workspace.
--
-- Until now `tenants.database_url` was the whole story: one workspace, one
-- connection string, and switching database meant switching workspace. That is a
-- reasonable model right up to the point where the same team owns two databases
-- and the same permission matrix should govern both.
--
-- Almost nothing has to change to support it, because the permission model was
-- already shaped this way. `table_grants`, `column_grants` and `grant_policies`
-- are all keyed `(tenant_id, data_source_id, ...)`, and migration 0010 keyed the
-- catalog the same way. The data source has been a first-class dimension
-- everywhere except in the one table that decides which databases exist.
--
-- Two things here.

-- ----------------------------------------------------------------------
-- The registry
-- ----------------------------------------------------------------------
--
-- `data_source_id` is the credential-free label `describe_data_source()` derives
-- from the URL -- `postgresql://db_postgres/chinook`. It is what every grant row
-- already carries, so a workspace's second database inherits the matrix machinery
-- with no translation layer.
--
-- The URL itself is encrypted exactly as `tenants.database_url` is, by the same
-- `Cipher`, and is never returned by an API that does not explicitly ask.

CREATE TABLE IF NOT EXISTS vanna_app.tenant_datasources (
    tenant_id       text        NOT NULL REFERENCES vanna_app.tenants(id) ON DELETE CASCADE,
    data_source_id  text        NOT NULL,

    -- Encrypted at rest. Same treatment as tenants.database_url.
    database_url    text        NOT NULL,

    -- What a human calls it. `data_source_id` is derived from the URL and changes
    -- if the workspace is repointed; this does not, so a screen has something
    -- stable to show.
    label           text        NOT NULL DEFAULT '',

    -- Which one a new conversation gets when nobody chooses. Exactly one per
    -- workspace, enforced by the partial unique index below -- "no default" and
    -- "two defaults" are both states where the answer to "which database?"
    -- depends on row order.
    is_default      boolean     NOT NULL DEFAULT false,

    is_active       boolean     NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (tenant_id, data_source_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS tenant_datasources_default_idx
    ON vanna_app.tenant_datasources (tenant_id)
    WHERE is_default;

-- Backfill, so no existing workspace changes behaviour.
--
-- Every tenant with a URL gets exactly one registered data source, marked
-- default, and the label is left blank so the UI falls back to the derived id.
-- A tenant with a NULL URL uses the server default and has nothing to register --
-- it keeps working through the same fallback it always did.
--
-- The id is computed by the application rather than here: `describe_data_source`
-- has dialect-specific rules (file-backed engines have no host, so the path is
-- the whole address) that are not worth reimplementing in SQL and would drift the
-- moment either copy changed. The application backfills on first boot; this
-- migration only makes the table exist.

-- ----------------------------------------------------------------------
-- Conversations remember which database they are about
-- ----------------------------------------------------------------------
--
-- The binding is per conversation, not per message. A thread's history is a
-- record of questions asked against one schema, and letting the target change
-- mid-thread means the model reads earlier turns describing tables that are no
-- longer in scope -- and that a client could switch database by editing one
-- header on one request.
--
-- NULL means "whatever the workspace default is", which is every conversation
-- that existed before this column did.
ALTER TABLE vanna_app.conversations
    ADD COLUMN IF NOT EXISTS data_source_id text;

-- ---- 0012_orphaned_conversations -----------------------------
-- Clean up conversations that were created without an owner.
--
-- `bind_data_source` pins a thread to one database, and it runs before the agent
-- has written anything -- so it inserts the row itself. It inserted
-- `user_id = ''`, and `_write`'s conflict predicate requires the owner to match,
-- so from that point on every transcript update for that thread was silently
-- discarded. The row was also invisible to `summaries`, `get_conversation` and
-- `delete_conversation`, all of which filter on the owner: a conversation nobody
-- could read, list, or delete.
--
-- The client sends a data source on the first message of every new thread once a
-- workspace has more than one database registered, so on such a workspace this
-- was every conversation started since that feature shipped.
--
-- The code fix is two parts, both already in place:
--   * `bind_data_source` records the caller, so new rows are owned from the start.
--   * `_write` adopts a `user_id = ''` row instead of rejecting it, so a thread
--     orphaned by the old behaviour recovers on its next turn.
--
-- That leaves the rows whose transcript was already lost. They have no owner and
-- an empty document, so there is nothing in them to recover and nobody they could
-- be shown to.
--
-- Deliberately narrow: `document` must still be the empty placeholder. A row with
-- an owner, or with messages in it, is left alone -- the adoption rule above will
-- claim it on the next turn, and destroying a transcript to tidy up a bug would be
-- a worse outcome than the bug.

DELETE FROM vanna_app.conversations
 WHERE user_id = ''
   AND coalesce(document->'messages', '[]'::jsonb) = '[]'::jsonb;

-- ---- 0013_datasource_health ----------------------------------
-- Remember whether a data source still answers.
--
-- `probe()` runs once, when a source is registered, and the result is thrown away
-- as soon as the request that asked for it ends. Nothing has recorded it since, so
-- a workspace whose warehouse password was rotated last week, or whose host moved,
-- looks identical to a healthy one until somebody asks a question and gets an
-- error they cannot interpret.
--
-- Three columns, deliberately not a separate table: this is the *current* state of
-- one row, not a history. A time series of connection checks is a monitoring
-- system's job, and inventing half of one here would mean growing a retention
-- policy for it.
--
-- Nullable, with no default: NULL means "never checked", which is a different
-- thing from "checked and healthy" and the console needs to say so differently.
-- A source registered before this migration is honestly unknown rather than
-- optimistically green.

ALTER TABLE vanna_app.tenant_datasources
    ADD COLUMN IF NOT EXISTS last_checked_at timestamptz,
    ADD COLUMN IF NOT EXISTS last_ok         boolean,
    -- Sanitised on the way in. A driver's connection error routinely contains the
    -- host, the user and occasionally the password it tried; this is shown in a
    -- browser to anyone who administers the workspace.
    ADD COLUMN IF NOT EXISTS last_error      text;

-- ---- 0014_configuration_catalog ------------------------------
-- Configuration moves into the database.
--
-- Every semantic project, instruction pack and domain definition this deployment
-- runs on is a file on disk, read at runtime: `vanna_project.yml`, `cubes/*.yml`,
-- `models/*/metadata.yml`, `relationships.yml`, `target/mdl.json`,
-- `instructions/baseline.yml`, `domains/domains.yml`. That works for a checkout
-- and stops working the moment an administrator wants to change a cube from a
-- browser -- there is nowhere for the change to go except a file in an image.
--
-- These two tables are where it goes instead. PostgreSQL becomes the runtime
-- source of truth; the files become the bootstrap import and the export artifact.
--
-- Two tables, not ten. A cube, a manifest and a pack have nothing in common
-- structurally, and giving each its own table means every new kind of
-- configuration file is a migration. `config_files` is deliberately generic so
-- that adding `backend/projects/newco/cubes/orders.yml` tomorrow is an import,
-- not a schema change.

-- ----------------------------------------------------------------------
-- The catalog
-- ----------------------------------------------------------------------
--
-- Three representations of one file, because no two of them are the same thing:
--
--   raw_content  the exact bytes, comments and all. What the exporter writes back
--                out and what a diff view shows. JSONB cannot reproduce a file.
--   parsed       the runtime representation. The importer pays the YAML parse
--                once so that four workers rebuilding a manifest do not each pay
--                it again, and so this is queryable.
--   checksum     SHA-256 of the raw bytes. Makes the import idempotent and makes
--                "the database is behind the files" a detectable state rather
--                than a suspicion.

CREATE TABLE IF NOT EXISTS vanna_app.config_files (
    id              bigserial   PRIMARY KEY,

    -- Who owns this file. `global` is platform content (the baseline, the packs,
    -- the domain definitions); `tenant` and `project` are one workspace's own.
    -- Without the distinction, every global pack would be duplicated per tenant.
    scope           text        NOT NULL
                    CHECK (scope IN ('global', 'tenant', 'project')),

    -- Empty strings rather than NULL, and that is not cosmetic: in PostgreSQL a
    -- UNIQUE constraint treats every NULL as distinct, so a nullable tenant_id
    -- would let the same global file be inserted any number of times and the
    -- constraint below would not object once.
    tenant_id       text        NOT NULL DEFAULT '',
    project         text        NOT NULL DEFAULT '',

    -- Relative to `backend/`, forward slashes on every platform:
    -- 'projects/chinook/cubes/sales.yml'. The path is the identity -- it is what
    -- the importer matches on and what the runtime asks for.
    relative_path   text        NOT NULL,

    -- Classified from the path by the importer: domain, instruction_baseline,
    -- instruction_pack, project_config, cube, model, relationships, manifest,
    -- knowledge_rule, eval_dataset, other. Not a CHECK constraint: a new kind
    -- must not need a migration, and an unrecognised path lands in `other` with
    -- its content intact rather than being rejected.
    kind            text        NOT NULL DEFAULT 'other',
    extension       text        NOT NULL DEFAULT '',

    checksum        text        NOT NULL,
    raw_content     text        NOT NULL,

    -- NULL when the file could not be parsed -- a `.md` knowledge rule, or a YAML
    -- file with a syntax error. Stored anyway, and reported by the importer:
    -- a file silently dropped is a configuration difference nobody finds.
    parsed          jsonb,

    metadata        jsonb       NOT NULL DEFAULT '{}'::jsonb,

    -- Bumped on every content change, and the join key for the history below.
    version         integer     NOT NULL DEFAULT 1,
    updated_by      text,

    imported_at     timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    UNIQUE (scope, tenant_id, project, relative_path)
);

-- The lookup the runtime actually makes: "everything of kind X for workspace Y".
CREATE INDEX IF NOT EXISTS config_files_scope_idx
    ON vanna_app.config_files (scope, tenant_id, project, kind);

-- Ask questions of the content without unnesting it per query --
-- `parsed @> '{"name": "customers"}'` across every model in every project.
CREATE INDEX IF NOT EXISTS config_files_parsed_idx
    ON vanna_app.config_files USING gin (parsed);

-- ----------------------------------------------------------------------
-- The history
-- ----------------------------------------------------------------------
--
-- Once configuration is edited from a browser rather than through a pull request,
-- the questions a pull request used to answer have to be answered here: who
-- changed this model, when, what did it look like before, and can I put it back.
--
-- A full copy per version rather than a diff. Configuration files are kilobytes,
-- there are dozens of them, and a stored diff needs the whole chain replayed to
-- answer "what was running last Tuesday" -- which is the only question this table
-- exists to answer.

CREATE TABLE IF NOT EXISTS vanna_app.config_versions (
    id              bigserial   PRIMARY KEY,
    config_file_id  bigint      NOT NULL
                    REFERENCES vanna_app.config_files(id) ON DELETE CASCADE,
    version         integer     NOT NULL,

    checksum        text        NOT NULL,
    raw_content     text        NOT NULL,
    parsed          jsonb,

    -- How it arrived: 'import' from a file, 'api' from an administrator.
    source          text        NOT NULL DEFAULT 'import'
                    CHECK (source IN ('import', 'api')),
    created_by      text,
    note            text,
    created_at      timestamptz NOT NULL DEFAULT now(),

    UNIQUE (config_file_id, version)
);

CREATE INDEX IF NOT EXISTS config_versions_file_idx
    ON vanna_app.config_versions (config_file_id, version DESC);

-- ---- the ledger ----------------------------------------------------
CREATE TABLE IF NOT EXISTS vanna_app.schema_migrations (
    version     integer     PRIMARY KEY,
    name        text        NOT NULL,
    applied_at  timestamptz NOT NULL DEFAULT now(),
    duration_ms integer     NOT NULL DEFAULT 0
);
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (1, $vanna$initial$vanna$, 197) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (2, $vanna$auth_hardening$vanna$, 18) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (3, $vanna$counters$vanna$, 24) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (4, $vanna$audit$vanna$, 60) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (5, $vanna$search_and_cost$vanna$, 35) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (6, $vanna$grants$vanna$, 67) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (7, $vanna$write_approvals$vanna$, 62) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (8, $vanna$instructions$vanna$, 57) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (9, $vanna$grant_defaults$vanna$, 22) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (10, $vanna$schema_catalog$vanna$, 601) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (11, $vanna$workspace_datasources$vanna$, 204) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (12, $vanna$orphaned_conversations$vanna$, 6) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (13, $vanna$datasource_health$vanna$, 7) ON CONFLICT (version) DO NOTHING;
INSERT INTO vanna_app.schema_migrations (version, name, duration_ms) VALUES (14, $vanna$configuration_catalog$vanna$, 67) ON CONFLICT (version) DO NOTHING;

COMMIT;
