"""Reading a project's YAML into a :class:`Manifest`, and building it out.

Two representations of the same thing, on purpose:

* **YAML, one file per model** -- what humans edit and review. A directory per
  model so two people editing two models never touch the same file.
* **``target/mdl.json``** -- one compiled document, what the compiler and the
  agent read. Derived, gitignored, and regenerated by ``vanna project build``.

Keeping them separate is what lets the edit format be pleasant (comments,
sidecar ``.sql`` files) while the runtime format stays a single parse.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import yaml

from ..core.errors import ErrorCode, ErrorPhase, VannaError
from ..project.layout import MODEL_METADATA, MODEL_REF_SQL, ProjectPaths
from .models import Cube, Manifest, Relationship, SemanticModel, View

logger = logging.getLogger(__name__)


def _read_yaml(path: Path) -> Dict[str, Any]:
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise VannaError(
            ErrorCode.INVALID_MANIFEST,
            f"{path} is not valid YAML.",
            phase=ErrorPhase.PROJECT_LOAD,
            cause=exc,
        )


def _as_model(raw: Dict[str, Any], *, source: Path) -> SemanticModel:
    try:
        return SemanticModel.model_validate(raw)
    except Exception as exc:
        raise VannaError(
            ErrorCode.INVALID_MANIFEST,
            f"{source}: {exc}",
            phase=ErrorPhase.PROJECT_LOAD,
            cause=exc,
        )


def load_manifest_from_project(paths: ProjectPaths, *, dialect: str = "") -> Manifest:
    """Assemble a manifest from a project's YAML tree."""
    model_documents: List[Tuple[str, Dict[str, Any]]] = []
    for model_dir in paths.model_dirs():
        raw = _read_yaml(model_dir / MODEL_METADATA)

        # A sidecar ref_sql.sql wins over an inline one: it is the form that
        # gets syntax highlighting and a sensible diff, so it is the form people
        # actually maintain.
        sidecar = model_dir / MODEL_REF_SQL
        if sidecar.is_file():
            text = sidecar.read_text(encoding="utf-8").strip()
            if text:
                raw["ref_sql"] = text

        model_documents.append((model_dir.name, raw))

    relationship_document: Dict[str, Any] = {}
    if paths.relationships_file.is_file():
        relationship_document = _read_yaml(paths.relationships_file)

    return manifest_from_documents(
        models=model_documents,
        relationships=relationship_document,
        cubes=[(path.stem, _read_yaml(path)) for path in paths.cube_files()],
        views=[
            (path.stem, path.read_text(encoding="utf-8").strip())
            for path in paths.view_files()
        ],
        dialect=dialect,
        where=str(paths.root),
    )


def manifest_from_documents(
    *,
    models: Sequence[Tuple[str, Dict[str, Any]]] = (),
    relationships: Optional[Dict[str, Any]] = None,
    cubes: Sequence[Tuple[str, Dict[str, Any]]] = (),
    views: Sequence[Tuple[str, str]] = (),
    dialect: str = "",
    where: str = "the project",
) -> Manifest:
    """Build and validate a manifest from already-parsed documents.

    The compilation step, separated from reading files, because the sources are no
    longer necessarily files: with configuration in the control plane they are rows,
    and an administrator editing a cube in a browser needs the same manifest built
    the same way. Two implementations of "compile a project" would drift, and the
    one that drifted would produce a manifest the file-based build does not --
    which is a difference nobody would notice until a query was refused.

    Each document is paired with the name it is filed under, so a model or cube
    that does not name itself still gets the name it is addressed by.
    """
    built_models: List[SemanticModel] = []
    for name, raw in models:
        document = dict(raw or {})
        document.setdefault("name", name)
        if document.get("ref_sql"):
            document.pop("refSql", None)
            # A model with a sidecar query has no table; carrying both would trip
            # the "exactly one source" rule at validation.
            document.pop("table_reference", None)
            document.pop("tableReference", None)
        built_models.append(_as_model(document, source=Path(where) / name))

    built_relationships: List[Relationship] = []
    for entry in (relationships or {}).get("relationships") or []:
        try:
            built_relationships.append(Relationship.model_validate(entry))
        except Exception as exc:
            raise VannaError(
                ErrorCode.INVALID_MANIFEST,
                f"{where}: relationship {entry!r}: {exc}",
                phase=ErrorPhase.PROJECT_LOAD,
                cause=exc,
            )

    built_cubes: List[Cube] = []
    for name, raw in cubes:
        document = dict(raw or {})
        document.setdefault("name", name)
        try:
            built_cubes.append(Cube.model_validate(document))
        except Exception as exc:
            raise VannaError(
                ErrorCode.INVALID_MANIFEST,
                f"{where}: cube {name}: {exc}",
                phase=ErrorPhase.PROJECT_LOAD,
                cause=exc,
            )

    return Manifest(
        models=built_models,
        relationships=built_relationships,
        cubes=built_cubes,
        views=[View(name=name, statement=statement) for name, statement in views],
        data_source=dialect or None,
    )


def build_manifest(paths: ProjectPaths, *, dialect: str = "") -> Path:
    """Compile the YAML tree to ``target/mdl.json`` and return its path."""
    manifest = load_manifest_from_project(paths, dialect=dialect)
    paths.target_dir.mkdir(parents=True, exist_ok=True)
    paths.manifest_file.write_text(
        json.dumps(manifest.to_json_dict(), indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    return paths.manifest_file


def load_built_manifest(paths: ProjectPaths) -> Optional[Manifest]:
    """Read ``target/mdl.json``, or None when it has not been built.

    None rather than raising: a deployment with no semantic layer is a supported
    configuration, and the caller decides whether that is a problem.
    """
    if not paths.manifest_file.is_file():
        return None
    try:
        return Manifest.from_json_dict(
            json.loads(paths.manifest_file.read_text(encoding="utf-8"))
        )
    except (json.JSONDecodeError, ValueError) as exc:
        raise VannaError(
            ErrorCode.INVALID_MANIFEST,
            f"{paths.manifest_file} could not be read.",
            phase=ErrorPhase.PROJECT_LOAD,
            hint="Rebuild it with `vanna project build`.",
            cause=exc,
        )


# ----------------------------------------------------------------------
# Writing YAML back out
# ----------------------------------------------------------------------


def write_model_yaml(paths: ProjectPaths, model: SemanticModel) -> Path:
    """Write one model's ``metadata.yml``, splitting out any ``ref_sql``."""
    model_dir = paths.models_dir / model.name
    model_dir.mkdir(parents=True, exist_ok=True)

    payload = model.model_dump(
        by_alias=False, exclude_none=True, exclude_defaults=True, mode="json"
    )
    payload["name"] = model.name

    ref_sql = payload.pop("ref_sql", None)
    if ref_sql:
        (model_dir / MODEL_REF_SQL).write_text(ref_sql.rstrip() + "\n", encoding="utf-8")

    target = model_dir / MODEL_METADATA
    target.write_text(
        yaml.safe_dump(payload, sort_keys=False, default_flow_style=False, width=100),
        encoding="utf-8",
    )
    return target


def write_relationships_yaml(
    paths: ProjectPaths, relationships: List[Relationship]
) -> Path:
    payload = {
        "relationships": [
            r.model_dump(by_alias=False, exclude_none=True, mode="json")
            for r in relationships
        ]
    }
    paths.relationships_file.write_text(
        yaml.safe_dump(payload, sort_keys=False, default_flow_style=False, width=100),
        encoding="utf-8",
    )
    return paths.relationships_file
