"""``python -m vanna`` — the command line interface.

This replaces the ``vanna`` console script. That script was generated by pip from
``[project.scripts]`` when the library was installed as a package, and there is no
installation step any more: the code is imported from source, so nothing puts a
launcher on PATH.

``python -m vanna`` is the equivalent that needs no packaging. It works from
``backend/`` with a bare virtual environment and takes exactly the arguments the
console script took:

    cd backend
    python -m vanna --help
    python -m vanna serve --port 8000
    python -m vanna ask "how many orders last month?"
"""

from __future__ import annotations

from .cli.main import main

raise SystemExit(main())
